#include "PlaceNameGenerator.h"

#include <stdio.h>
#include <string.h>

static const char *placeNames[] =
{
    ".Abaddon",
    ".Agony",
    ".Alcazar",
    ".Gehenna",
    "Heaven",
    "Hell",
    ".Heaven",
    ".Hell",
    ".Hellfire",
    ".Limbo",
    ".Pandemonium",
    ".Perdition",
    ".Purgatory",
    "Space",
    ".Space",
    ".Suffering",
    "Abbey",
    "Abode",
    "Abyss",
    "Acropolis",
    "Hideaway",
    "Alcove",
    "Antechamber",
    "Asylum",
    "Balcony",
    "Barrier",
    "Bastion",
    "Black-Hole",
    "Bottomless-Pit",
    "Bridge",
    "Burrow",
    "Cage",
    "Camp",
    "Canyon",
    "Castellum",
    "Castle",
    "Cathedral",
    "Cave",
    "Cavity",
    "Cell",
    "Chamber",
    "Chapel",
    "Citadel",
    "Cloister",
    "Closure",
    "Confinement",
    "Convent",
    "Corner",
    "Cortege",
    "Court",
    "Courtyard",
    "Cranny",
    "Crevice",
    "Crypt",
    "Cult",
    "Den",
    "Donjon",
    "Dungeon",
    "Dwelling",
    "Encampment",
    "Enclosure",
    "Everlasting-Fire",
    "Fasthold",
    "Fence",
    "Fold",
    "Fort",
    "Fortification",
    "Fortress",
    "Friary",
    "Gallery",
    "Garden",
    "Gorge",
    "Grave",
    "Graveyard",
    "Grounds",
    "Guardhouse",
    "Hall",
    "Nest",
    "Haven",
    "Hearth",
    "Hedge",
    "Hereafter",
    "Hermitage",
    "Hold",
    "Hole",
    "Hollow",
    "House",
    "Household",
    "Inferno",
    ".Inferno",
    "Jail",
    "Keep",
    ".Keep",
    "Lamasery",
    "Lockup",
    "Lowerworld",
    "Manor",
    "Mansion",
    "Monastery",
    "Mouth",
    "Necropolis",
    "Netherworld",
    "Niche",
    "Nightmare",
    "Nook",
    "Opening",
    "Otherworld",
    "Oubliette",
    "Outlet",
    "Overlook",
    "Palace",
    "Patch",
    "Pit",
    "Plot",
    "Priory",
    "Prison",
    "Recess",
    "Redoubt",
    "Region",
    "Retinue",
    "Retreat",
    "Rift",
    "Rincon",
    "Room",
    "Roost",
    "Safehold",
    "Sanctuary",
    "Seat",
    "Settlement",
    "Stall",
    "Stockade",
    "Stronghold",
    "Sty",
    "Terrace",
    "Torture-Chamber",
    "Tower",
    "Underworld",
    "Vault",
    "Veranda",
    "Walk",
    "Catwalk",
    "Wall",
    "Waypoint",
    "Yard",
    "Zone",
    0
};

static const char *adjectives[] = 
{
    "Acclaimed",
    "Reanimated",
    "Aristocratic",
    "Atrocious",
    "August",
    "Authoritative",
    "Azure",
    "Baneful",
    "Baronial",
    "Base",
    "Beastly",
    "Bedraggled",
    "Begrimed",
    "Beryl",
    "Bittersweet",
    "Black",
    "Bloodshot",
    "Blooming",
    "Blue",
    "Gray",
    "Emerald",
    "Bony",
    "Brilliant",
    "Cacodemonic",
    "Cadaverous",
    "Calamitous",
    "Cardinal",
    "Celebrated",
    "Cerulean",
    "Cobalt",
    "Commanding",
    "Conspicuous",
    "Coral",
    "Corrupt",
    "Crimson",
    "Dahlia",
    "Damnable",
    "Defiled",
    "Demonic",
    "Desolate",
    "Destructive",
    "Devilish",
    "Diabolic",
    "Dignified",
    "Dirty",
    "Disastrous",
    "Dismal",
    "Distinguished",
    "Dreary",
    "Elevated",
    "Eminent",
    "Energumenical",
    "Especial",
    "Esteemed",
    "Evil",
    "Execrable",
    "Extraordinary",
    "Famed",
    "Famous",
    "Filthy",
    "Flagitious",
    "Flaming",
    "Florid",
    "Flushed",
    "Forbidding",
    "Foremost",
    "Forlorn",
    "Foul",
    "Garnet",
    "Glorious",
    "Glowing",
    "Goetic",
    "Grandiose",
    "Great",
    "Grim",
    "Haggard",
    "Harsh",
    "Hateful",
    "Heinous",
    "Hellish",
    "Hideous",
    "High",
    "Highborn",
    "Highly-Regarded",
    "Holy",
    "Honorable",
    "Honored",
    "Illustrious",
    "Immoral",
    "Imperial",
    "Impure",
    "Indigo",
    "Inflamed",
    "Iniquitous",
    "Injurious",
    "Kingly",
    "Lenocinant",
    "Loathsome",
    "Lofty",
    "Low",
    "Magnificent",
    "Majestic",
    "Malefic",
    "Maleficent",
    "Malevolent",
    "Malicious",
    "Malignant",
    "Malominous",
    "Meager",
    "Miry",
    "Murky",
    "Nasty",
    "Nefarious",
    "Noble",
    "Nonpareil",
    "Noteworthy",
    "Obscene",
    "Offensive",
    "Outstanding",
    "Peccant",
    "Peerless",
    "Pernicious",
    "Poison",
    "Polluted",
    "Prominent",
    "Putrid",
    "Queenly",
    "Rancorous",
    "Raunchy",
    "Red",
    "Regal",
    "Regnant",
    "Reigning",
    "Remarkable",
    "Renowned",
    "Reprobate",
    "Repugnant",
    "Resplendent",
    "Revolting",
    "Rose",
    "Roseate",
    "Royal",
    "Rubicund",
    "Ruby",
    "Ruling",
    "Rusty",
    "Sanguine",
    "Sapphire",
    "Satanic",
    "Scarlet",
    "Scelerate",
    "Sea-blue",
    "Shining",
    "Sinful",
    "Sinistral",
    "Skeletal",
    "Soiled",
    "Sovereign",
    "Spare",
    "Spiteful",
    "Splendid",
    "Squalid",
    "Stained",
    "Stately",
    "Stinking",
    "Striking",
    "Superb",
    "Superior",
    "Supreme",
    "Teal",
    "Titian",
    "Tortious",
    "Turquoise",
    "Ugly",
    "Ultramarine",
    "Unclean",
    "Undead",
    "Unforgettable",
    "Unholy",
    "Unpleasant",
    "Unpropitious",
    "Unsightly",
    "Unwashed",
    "Venal",
    "Venerable",
    "Vermilion",
    "Verminous",
    "Vicious",
    "Vile",
    "Vital",
    "Villainous",
    "Wasted",
    "Well-known",
    "Wicked",
    "Essential",
    "Worthy",
    "Wrathful",
    "Wrong",
    "Zoetic",
    "Arsenic",
    "Alizarin",
    "Amaranth",
    "Amber",
    "Amethyst",
    "Ancient",
    "Azure",
    "Black",
    "Brass",
    "Cerulean",
    "Bronze",
    "Copper",
    "Iron",
    "Steel",
    "Gold",
    "Golden",
    "Brown",
    "Burnt",
    "Pale",
    "Faded",
    "Byzantine",
    "Cadmium",
    "Cardinal",
    "Charcoal",
    "Coal",
    "Coral",
    "Crimson",
    "Dark",
    "Lava",
    "Red",
    "Ash",
    "Ashen",
    "Slate",
    "Desert",
    "Frozen",
    "Freezing",
    "Flaming",
    "Fawn",
    "Flaxen",
    "Weeping",
    "Ghostly",
    "Shimmering",
    "Ivory",
    "Jade",
    "Indigo",
    "Magic",
    "Enchanted",
    "Light",
    "Onyx",
    "Drab",
    "Pearl",
    "Platinum",
    "Umber",
    "Ruby",
    "Rust",
    "Silver",
    "Snowy",
    "Mortal",
    "Torched",
    "Turkish",
    "Twilight",
    "Vermilion",
    "Violet",
    "Violent",
    "Vivid",
    "Viridian",
    "Mindful",
    "Mindless",
    "Cold",
    "White",
    "Spiny",

    0
};

static const char *names[] =
{
    ".Attila",
    ".Bones",
    ".Bugul-Noz",
    ".Diavolus",
    ".Fenris",
    ".Lilith",
    ".Lucius",
    ".Lucretia",
    ".Machiavelli",
    ".Man",
    ".Manichea",
    ".Pan",
    ".Pandora",
    ".Talos",
    ".Tarquinius",
    ".Typhon",
    ".Woman",
    ".Xana",
    ".Zana",
    "Air-Elemental",
    "Angel",
    "Ankou",
    "Arachnid",
    "Arion",
    "Asp",
    "Axe",
    "Balrog",
    "Banshee",
    "Barbarian",
    "Basilisk",
    "Beast",
    "Behemoth",
    "Black-Annis",
    "Bone-Cage",
    "Boor",
    "Brute",
    "Cadaver",
    "Cannibal",
    "Carcass",
    "Cecaelia",
    "Centaur",
    "Changeling",
    "Child",
    "Chimaera",
    "Cockatrice",
    "Corpse",
    "Creature",
    "Critter",
    "Crocotta",
    "Crow",
    "Cwn-Annwn",
    "Cyclops",
    "Daemon",
    "Dahlia",
    "Daphnaie",
    "Dark-Elf",
    "Dead",
    "Dead-Body",
    "Deceased",
    "Demigod",
    "Demon",
    "Devil",
    "Diavolus",
    "Drac",
    "Dragon",
    "Drake",
    "Dryad",
    "Duende",
    "Dvergr",
    "Dwarf",
    "Earth-Elemental",
    "Elephant",
    "Elf",
    "Enchanted",
    "Ettin",
    "Fachen",
    "Fairy",
    "Familiar",
    "Faun",
    "Fiend",
    "Fire-Elemental",
    "Fire-Giant",
    "Firedrake",
    "Flesh",
    "Flesh-and-Blood",
    "Fool",
    "Fox",
    "Frost-Giant",
    "Gargoyle",
    "Garmr",
    "Genius-Loci",
    "Ghost",
    "Ghoul",
    "Giant",
    "Gigantes",
    "Glutton",
    "Gnome",
    "Goblin",
    "Golem",
    "Gorgades",
    "Gorgon",
    "Gravedigger",
    "Gryphon",
    "Hag",
    "Half-Elf",
    "Hellhound",
    "Hesperides",
    "Hob",
    "Hobgoblin",
    "River",
    "Hog",
    "Hooligan",
    "Houri",
    "Hun",
    "Hydra",
    "Ice-Giant",
    "Ignoramus",
    "Incubus",
    "Indus-Worm",
    "Jaculus",
    "Jormungandr",
    "King",
    "Knocker",
    "Kobold",
    "Kraken",
    "Ladon",
    "Lady-Midday",
    "Landvaettir",
    "Leviathan",
    "Lily",
    "Lizard",
    "Ljosalfar",
    "Llorona",
    "Lout",
    "Lynx",
    "Macrocephali",
    "Mage",
    "Magician",
    "Mandrake",
    "Manes",
    "Manticore",
    "Mara",
    ".Medusa",
    "Meliae",
    ".Melusine",
    ".Mephisto",
    "Minotaur",
    "Monocerus",
    "Monster",
    "Monstrosity",
    "Mortal",
    "Muse",
    "Naiad",
    "Necromancer",
    "Nephilim",
    "Nereid",
    "Nix",
    "Nymph",
    "Ogre",
    "Orc",
    "Ouroboros",
    "Patagon",
    "Philistine",
    "Phoenix",
    "Pig",
    "Pixie",
    "Poltergeist",
    "Prince",
    "Princess",
    "Pygmy",
    "Quadruped",
    "Queen",
    "Quinotaur",
    "Rarog",
    "Rascal",
    "Raven",
    "Remains",
    "Revenant",
    "Rok",
    "Rose",
    "Ruffian",
    "Salamander",
    "Satyr",
    "Satyrus",
    "Scorpion",
    "Seductress",
    "Serpent",
    "Shade",
    "Shipwreck",
    "Siren",
    "Sjoraa",
    "Sjovaettir",
    "Skeleton",
    "Skogsraa",
    "Sloven",
    "Snake",
    "Soul",
    "Spectre",
    "Sphinx",
    "Spider",
    "Sprite",
    "Stiff",
    "Succubus",
    "Svartalfar",
    "Swan-Maiden",
    "Swine",
    "Sword",
    "Troglodyte",
    "Troll",
    ".Tzitzimitl",
    "Undead",
    ".Undine",
    "Unicorn",
    "Vaettir",
    "Valkyrie",
    "Vandal",
    "Viper",
    "Warg",
    "Warthog",
    "Water-Elemental",
    "White-Lady",
    "Wight",
    "Wizard",
    "Worm",
    "Wraith",
    "Wyrm",
    "Wyvern",
    "Zombie",
    ".Flame",
    ".Earth",
    ".Ice",
    ".Air",
    ".Light",
    ".Dark",
    ".Darkness",
    ".Water",
    ".Soil",
    "Iceberg",
    "Iris",
    ".Lust",
    ".Snow",
    "Torch",
    "Albatross",
    "Aardwolf",
    "Anaconda",
    "Ape",
    "Basilisk",
    "Bat",
    "Bear",
    "Widow",
    "Widower",
    "Bereaved",
    "Agrieved",
    "Stricken",
    "Despairing",
    "Blackbird",
    "Cardinal",
    "Carp",
    "Chameleon",
    "Cobra",
    "Cockroach",
    "Condor",
    "Constrictor",
    "Cricket",
    "Damselfly",
    "Dove",
    "Dragonfly",
    "Eel",
    "Falcon",
    "Ferret",
    "Firefly",
    "Fly",
    "Fowl",
    "Frog",
    "Squid",
    "Goat",
    "Gull",
    "Hare",
    "Heron",
    "Hornet",
    "Hyena",
    "Iguana",
    "Jackal",
    "Lamprey",
    "Leech",
    "Lemur",
    "Locust",
    "Louse",
    "Macaw",
    "Magpie",
    "Marten",
    "Meadowlark",
    "Mink",
    "Mole",
    "Mongoose",
    "Monkey",
    "Octopus",
    "Owl",
    "Ox",
    "Platypus",
    "Python",
    "Rat",
    "Rattlesnake",
    "Raven",
    "Rook",
    "Salamander",
    "Scorpion",
    "Shrew",
    "Skink",
    "Sloth",
    "Slug",
    "Snail",
    "Sturgeon",
    "Swan",
    "Toad",    
    "Tortoise",
    "Turtle",
    "Urial",
    "Vulture",
    "Wasp",
    "Wolf",
    "Weasel",
    "Wolverine",
    "Wren",
    "Reaver",
    "Yak",

"Alder",
"Ambrosia",
"Ash",
"River Ash",
"Azolla",
".Bindweed",
".Bittercress",
"Brier",
"Chrysanthemum",
".Colic Weed",
"Devil's Bite",
"Devil's Plague",
"Fellenwort",
"Fern",
".Garlic",
".Golden Garlic",
".Laceflower",
".Milkwood",
"Mother",
".Nightshade",
"Onion",
"Rose",
"Dwarf Wild Rose",
"Sanguinary",
"Silkweed",
"Thistle",
"Sharp",
".Toothwort",
"Tulip",
".Leatherleaf",
".Viburnum",
"Bloom",
"Bower",
".Waybread",
"Willow",
"Windroot",
"Wintercress",
".Wormwood",
".Wormroot",
"Yarrow",
".Sneezewort",
"Zinnia",

    0
};

static int GetCount(const char **list)
{
    const char **p = list;
    int i = 0;
    for (; *p; i++) p++;
    return i;
}

PlaceNameGenerator::PlaceNameGenerator() : mAdjectivesCount(0), mPlaceNamesCount(0), mNamesCount(0)
{
    mAdjectivesCount = GetCount(adjectives);
    mPlaceNamesCount = GetCount(placeNames);
    mNamesCount      = GetCount(names);
}

const char *PlaceNameGenerator::FormatName2(const char *adjective, const char *placeName, const char *name) const
{
    static char buffer[1024];

    bool        placeNameThe = *placeName != '.',
                nameThe      = *name      != '.';

    const char *separator    = " ";

    if (!placeNameThe) placeName++;
    if (!nameThe)      name++;
    if (!adjective)    { adjective = ""; separator = ""; }

    if      (nameThe)
        sprintf(buffer, "The %s's %s%s%s", name, adjective, separator, placeName);
    else if (!nameThe)
        sprintf(buffer, "%s's %s%s%s", name, adjective, separator, placeName);
    /*
    else if (!placeNameThe &&  nameThe)
        //sprintf(buffer, "%s %s of the %s", adjective, placeName, name);
        sprintf(buffer, "%s of the %s", placeName, name);
    else if (!placeNameThe && !nameThe)
        //sprintf(buffer, "%s %s of %s", adjective, placeName, name);
        sprintf(buffer, "%s of %s", placeName, name);
    */

    return buffer;
}

const char *PlaceNameGenerator::FormatName1(const char *adjective, const char *placeName, const char *name) const
{
    static char buffer[1024];

    bool        placeNameThe = *placeName != '.',
                nameThe      = *name      != '.';

    const char *separator    = " ";

    if (!placeNameThe) placeName++;
    if (!nameThe)      name++;
    if (!adjective)    { adjective = ""; separator = ""; }

    if      ( placeNameThe &&  nameThe)
        sprintf(buffer, "The %s%s%s of the %s", adjective, separator, placeName, name);
    else if ( placeNameThe && !nameThe)
        sprintf(buffer, "The %s%s%s of %s", adjective, separator, placeName, name);
    else if (!placeNameThe &&  nameThe)
        sprintf(buffer, "%s%s%s of the %s", adjective, separator, placeName, name);
    else if (!placeNameThe && !nameThe)
        sprintf(buffer, "%s%s%s of %s", adjective, separator, placeName, name);

    return buffer;
}

const char *PlaceNameGenerator::GetPlaceName(core::Random &random) const
{
    int number0 = random.integer(),
        number1 = random.integer(),
        number2 = random.integer();

    const char *adjective = adjectives[number0 % mAdjectivesCount];
    const char *placeName = placeNames[number1 % mPlaceNamesCount];
    const char *name      = names     [number2 % mNamesCount];

    if (random.realf() < 0.5f) adjective = 0;

    const char *formatted = 0;
    if (random.realf() < 0.5f) formatted = FormatName1(adjective, placeName, name);
    else                       formatted = FormatName2(adjective, placeName, name);

    strcpy(mName, formatted);
    return mName;
}