/**************************************************************************************************/
/*!
    \file c:\tmp\franchisestress.h

    \attention
        (c) Electronic Arts Inc. 2007-2009

    \note DO NOT EDIT THIS FILE!
          This file was auto-generated by typeComp from \verbatim C:\DEV\blaze\games\Madden\2010-NG\trunk\component\franchise\gen\franchise.tdf \endverbatim 
*/

/**************************************************************************************************/

#ifndef C__DEV_BLAZE_GAMES_MADDEN_2010_NG_TRUNK_COMPONENT_FRANCHISE_GEN_FRANCHISE_STRESS_H
#define C__DEV_BLAZE_GAMES_MADDEN_2010_NG_TRUNK_COMPONENT_FRANCHISE_GEN_FRANCHISE_STRESS_H

#include "framework/tdf/tdf.h"
#include "EASTL/vector.h"

#include "EASTL/vector_map.h"

#include "framework/callback.h"

#include "framework/tdf/userdefines.h"
#include "luathread.h"

#include "franchise/tdf/franchise.h"

namespace Blaze
{
namespace Stress
{

// FranchiseUser
LuaTable ConvertToLua_FranchiseUser   (LuaThread *lua, const Blaze::Franchise::FranchiseUser &value);
void     ConvertFromLua_FranchiseUser (LuaThread *lua, LuaTable table, Blaze::Franchise::FranchiseUser &value);

// AthleteDescription
LuaTable ConvertToLua_AthleteDescription   (LuaThread *lua, const Blaze::Franchise::AthleteDescription &value);
void     ConvertFromLua_AthleteDescription (LuaThread *lua, LuaTable table, Blaze::Franchise::AthleteDescription &value);

// AthleteProperties
LuaTable ConvertToLua_AthleteProperties   (LuaThread *lua, const Blaze::Franchise::AthleteProperties &value);
void     ConvertFromLua_AthleteProperties (LuaThread *lua, LuaTable table, Blaze::Franchise::AthleteProperties &value);

// DisplayRosterEntity
LuaTable ConvertToLua_DisplayRosterEntity   (LuaThread *lua, const Blaze::Franchise::DisplayRosterEntity &value);
void     ConvertFromLua_DisplayRosterEntity (LuaThread *lua, LuaTable table, Blaze::Franchise::DisplayRosterEntity &value);

// DepthChartUploadElement
LuaTable ConvertToLua_DepthChartUploadElement   (LuaThread *lua, const Blaze::Franchise::DepthChartUploadElement &value);
void     ConvertFromLua_DepthChartUploadElement (LuaThread *lua, LuaTable table, Blaze::Franchise::DepthChartUploadElement &value);

// DepthChartEntity
LuaTable ConvertToLua_DepthChartEntity   (LuaThread *lua, const Blaze::Franchise::DepthChartEntity &value);
void     ConvertFromLua_DepthChartEntity (LuaThread *lua, LuaTable table, Blaze::Franchise::DepthChartEntity &value);

// NewsItem
LuaTable ConvertToLua_NewsItem   (LuaThread *lua, const Blaze::Franchise::NewsItem &value);
void     ConvertFromLua_NewsItem (LuaThread *lua, LuaTable table, Blaze::Franchise::NewsItem &value);

// PersonaMapEntry
LuaTable ConvertToLua_PersonaMapEntry   (LuaThread *lua, const Blaze::Franchise::PersonaMapEntry &value);
void     ConvertFromLua_PersonaMapEntry (LuaThread *lua, LuaTable table, Blaze::Franchise::PersonaMapEntry &value);

// PersonaMap
LuaTable ConvertToLua_PersonaMap   (LuaThread *lua, const Blaze::Franchise::PersonaMap &value);
void     ConvertFromLua_PersonaMap (LuaThread *lua, LuaTable table, Blaze::Franchise::PersonaMap &value);

// SubmitStatisticsRequest
LuaTable ConvertToLua_SubmitStatisticsRequest   (LuaThread *lua, const Blaze::Franchise::SubmitStatisticsRequest &value);
void     ConvertFromLua_SubmitStatisticsRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::SubmitStatisticsRequest &value);

// MemberStats
LuaTable ConvertToLua_MemberStats   (LuaThread *lua, const Blaze::Franchise::MemberStats &value);
void     ConvertFromLua_MemberStats (LuaThread *lua, LuaTable table, Blaze::Franchise::MemberStats &value);

// GetDraftableAthletesRequest
LuaTable ConvertToLua_GetDraftableAthletesRequest   (LuaThread *lua, const Blaze::Franchise::GetDraftableAthletesRequest &value);
void     ConvertFromLua_GetDraftableAthletesRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetDraftableAthletesRequest &value);

// DraftableAthlete
LuaTable ConvertToLua_DraftableAthlete   (LuaThread *lua, const Blaze::Franchise::DraftableAthlete &value);
void     ConvertFromLua_DraftableAthlete (LuaThread *lua, LuaTable table, Blaze::Franchise::DraftableAthlete &value);

// GetDraftableAthletesResponse
LuaTable ConvertToLua_GetDraftableAthletesResponse   (LuaThread *lua, const Blaze::Franchise::GetDraftableAthletesResponse &value);
void     ConvertFromLua_GetDraftableAthletesResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::GetDraftableAthletesResponse &value);

// PositionPref
LuaTable ConvertToLua_PositionPref   (LuaThread *lua, const Blaze::Franchise::PositionPref &value);
void     ConvertFromLua_PositionPref (LuaThread *lua, LuaTable table, Blaze::Franchise::PositionPref &value);

// DraftProfile
LuaTable ConvertToLua_DraftProfile   (LuaThread *lua, const Blaze::Franchise::DraftProfile &value);
void     ConvertFromLua_DraftProfile (LuaThread *lua, LuaTable table, Blaze::Franchise::DraftProfile &value);

// SetDraftProfileRequest
LuaTable ConvertToLua_SetDraftProfileRequest   (LuaThread *lua, const Blaze::Franchise::SetDraftProfileRequest &value);
void     ConvertFromLua_SetDraftProfileRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::SetDraftProfileRequest &value);

// GetDraftProfileRequest
LuaTable ConvertToLua_GetDraftProfileRequest   (LuaThread *lua, const Blaze::Franchise::GetDraftProfileRequest &value);
void     ConvertFromLua_GetDraftProfileRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetDraftProfileRequest &value);

// FranchiseError
LuaTable ConvertToLua_FranchiseError   (LuaThread *lua, const Blaze::Franchise::FranchiseError &value);
void     ConvertFromLua_FranchiseError (LuaThread *lua, LuaTable table, Blaze::Franchise::FranchiseError &value);

// Franchise
LuaTable ConvertToLua_Franchise   (LuaThread *lua, const Blaze::Franchise::Franchise &value);
void     ConvertFromLua_Franchise (LuaThread *lua, LuaTable table, Blaze::Franchise::Franchise &value);

// MemberInfo
LuaTable ConvertToLua_MemberInfo   (LuaThread *lua, const Blaze::Franchise::MemberInfo &value);
void     ConvertFromLua_MemberInfo (LuaThread *lua, LuaTable table, Blaze::Franchise::MemberInfo &value);

// CreateFranchiseRequest
LuaTable ConvertToLua_CreateFranchiseRequest   (LuaThread *lua, const Blaze::Franchise::CreateFranchiseRequest &value);
void     ConvertFromLua_CreateFranchiseRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::CreateFranchiseRequest &value);

// CreateFranchiseResponse
LuaTable ConvertToLua_CreateFranchiseResponse   (LuaThread *lua, const Blaze::Franchise::CreateFranchiseResponse &value);
void     ConvertFromLua_CreateFranchiseResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::CreateFranchiseResponse &value);

// JoinFranchiseRequest
LuaTable ConvertToLua_JoinFranchiseRequest   (LuaThread *lua, const Blaze::Franchise::JoinFranchiseRequest &value);
void     ConvertFromLua_JoinFranchiseRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::JoinFranchiseRequest &value);

// FindFranchisesRequest
LuaTable ConvertToLua_FindFranchisesRequest   (LuaThread *lua, const Blaze::Franchise::FindFranchisesRequest &value);
void     ConvertFromLua_FindFranchisesRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::FindFranchisesRequest &value);

// GetFranchisesByUserRequest
LuaTable ConvertToLua_GetFranchisesByUserRequest   (LuaThread *lua, const Blaze::Franchise::GetFranchisesByUserRequest &value);
void     ConvertFromLua_GetFranchisesByUserRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetFranchisesByUserRequest &value);

// FindFranchisesResponse
LuaTable ConvertToLua_FindFranchisesResponse   (LuaThread *lua, const Blaze::Franchise::FindFranchisesResponse &value);
void     ConvertFromLua_FindFranchisesResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::FindFranchisesResponse &value);

// FindFranchisesAsyncNotification
LuaTable ConvertToLua_FindFranchisesAsyncNotification   (LuaThread *lua, const Blaze::Franchise::FindFranchisesAsyncNotification &value);
void     ConvertFromLua_FindFranchisesAsyncNotification (LuaThread *lua, LuaTable table, Blaze::Franchise::FindFranchisesAsyncNotification &value);

// GetFranchiseRequest
LuaTable ConvertToLua_GetFranchiseRequest   (LuaThread *lua, const Blaze::Franchise::GetFranchiseRequest &value);
void     ConvertFromLua_GetFranchiseRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetFranchiseRequest &value);

// DeleteFranchiseRequest
LuaTable ConvertToLua_DeleteFranchiseRequest   (LuaThread *lua, const Blaze::Franchise::DeleteFranchiseRequest &value);
void     ConvertFromLua_DeleteFranchiseRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::DeleteFranchiseRequest &value);

// UpdateFranchiseSettingsRequest
LuaTable ConvertToLua_UpdateFranchiseSettingsRequest   (LuaThread *lua, const Blaze::Franchise::UpdateFranchiseSettingsRequest &value);
void     ConvertFromLua_UpdateFranchiseSettingsRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::UpdateFranchiseSettingsRequest &value);

// GetMemberByBlazeIdRequest
LuaTable ConvertToLua_GetMemberByBlazeIdRequest   (LuaThread *lua, const Blaze::Franchise::GetMemberByBlazeIdRequest &value);
void     ConvertFromLua_GetMemberByBlazeIdRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetMemberByBlazeIdRequest &value);

// GetMemberByTeamIdRequest
LuaTable ConvertToLua_GetMemberByTeamIdRequest   (LuaThread *lua, const Blaze::Franchise::GetMemberByTeamIdRequest &value);
void     ConvertFromLua_GetMemberByTeamIdRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetMemberByTeamIdRequest &value);

// GetMembersRequest
LuaTable ConvertToLua_GetMembersRequest   (LuaThread *lua, const Blaze::Franchise::GetMembersRequest &value);
void     ConvertFromLua_GetMembersRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetMembersRequest &value);

// GetMembersResponse
LuaTable ConvertToLua_GetMembersResponse   (LuaThread *lua, const Blaze::Franchise::GetMembersResponse &value);
void     ConvertFromLua_GetMembersResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::GetMembersResponse &value);

// RemoveMemberRequest
LuaTable ConvertToLua_RemoveMemberRequest   (LuaThread *lua, const Blaze::Franchise::RemoveMemberRequest &value);
void     ConvertFromLua_RemoveMemberRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::RemoveMemberRequest &value);

// PromoteToGMRequest
LuaTable ConvertToLua_PromoteToGMRequest   (LuaThread *lua, const Blaze::Franchise::PromoteToGMRequest &value);
void     ConvertFromLua_PromoteToGMRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::PromoteToGMRequest &value);

// BanMemberRequest
LuaTable ConvertToLua_BanMemberRequest   (LuaThread *lua, const Blaze::Franchise::BanMemberRequest &value);
void     ConvertFromLua_BanMemberRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::BanMemberRequest &value);

// ClearBanRequest
LuaTable ConvertToLua_ClearBanRequest   (LuaThread *lua, const Blaze::Franchise::ClearBanRequest &value);
void     ConvertFromLua_ClearBanRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::ClearBanRequest &value);

// CheckBanRequest
LuaTable ConvertToLua_CheckBanRequest   (LuaThread *lua, const Blaze::Franchise::CheckBanRequest &value);
void     ConvertFromLua_CheckBanRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::CheckBanRequest &value);

// CheckBanResponse
LuaTable ConvertToLua_CheckBanResponse   (LuaThread *lua, const Blaze::Franchise::CheckBanResponse &value);
void     ConvertFromLua_CheckBanResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::CheckBanResponse &value);

// Invitation
LuaTable ConvertToLua_Invitation   (LuaThread *lua, const Blaze::Franchise::Invitation &value);
void     ConvertFromLua_Invitation (LuaThread *lua, LuaTable table, Blaze::Franchise::Invitation &value);

// GetInvitationsResponse
LuaTable ConvertToLua_GetInvitationsResponse   (LuaThread *lua, const Blaze::Franchise::GetInvitationsResponse &value);
void     ConvertFromLua_GetInvitationsResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::GetInvitationsResponse &value);

// SendInvitationRequest
LuaTable ConvertToLua_SendInvitationRequest   (LuaThread *lua, const Blaze::Franchise::SendInvitationRequest &value);
void     ConvertFromLua_SendInvitationRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::SendInvitationRequest &value);

// GetInvitationsRequest
LuaTable ConvertToLua_GetInvitationsRequest   (LuaThread *lua, const Blaze::Franchise::GetInvitationsRequest &value);
void     ConvertFromLua_GetInvitationsRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetInvitationsRequest &value);

// ProcessInvitationRequest
LuaTable ConvertToLua_ProcessInvitationRequest   (LuaThread *lua, const Blaze::Franchise::ProcessInvitationRequest &value);
void     ConvertFromLua_ProcessInvitationRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::ProcessInvitationRequest &value);

// SetMemberStatusRequest
LuaTable ConvertToLua_SetMemberStatusRequest   (LuaThread *lua, const Blaze::Franchise::SetMemberStatusRequest &value);
void     ConvertFromLua_SetMemberStatusRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::SetMemberStatusRequest &value);

// SetJerseyNumberRequest
LuaTable ConvertToLua_SetJerseyNumberRequest   (LuaThread *lua, const Blaze::Franchise::SetJerseyNumberRequest &value);
void     ConvertFromLua_SetJerseyNumberRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::SetJerseyNumberRequest &value);

// SetDefaultRosterRequest
LuaTable ConvertToLua_SetDefaultRosterRequest   (LuaThread *lua, const Blaze::Franchise::SetDefaultRosterRequest &value);
void     ConvertFromLua_SetDefaultRosterRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::SetDefaultRosterRequest &value);

// SetDefaultSchedulesRequest
LuaTable ConvertToLua_SetDefaultSchedulesRequest   (LuaThread *lua, const Blaze::Franchise::SetDefaultSchedulesRequest &value);
void     ConvertFromLua_SetDefaultSchedulesRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::SetDefaultSchedulesRequest &value);

// SetNewSeasonStandingsRequest
LuaTable ConvertToLua_SetNewSeasonStandingsRequest   (LuaThread *lua, const Blaze::Franchise::SetNewSeasonStandingsRequest &value);
void     ConvertFromLua_SetNewSeasonStandingsRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::SetNewSeasonStandingsRequest &value);

// GameplayRoster
LuaTable ConvertToLua_GameplayRoster   (LuaThread *lua, const Blaze::Franchise::GameplayRoster &value);
void     ConvertFromLua_GameplayRoster (LuaThread *lua, LuaTable table, Blaze::Franchise::GameplayRoster &value);

// GetGameplayRosterRequest
LuaTable ConvertToLua_GetGameplayRosterRequest   (LuaThread *lua, const Blaze::Franchise::GetGameplayRosterRequest &value);
void     ConvertFromLua_GetGameplayRosterRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetGameplayRosterRequest &value);

// GetDisplayRosterResponse
LuaTable ConvertToLua_GetDisplayRosterResponse   (LuaThread *lua, const Blaze::Franchise::GetDisplayRosterResponse &value);
void     ConvertFromLua_GetDisplayRosterResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::GetDisplayRosterResponse &value);

// GetDisplayRosterRequest
LuaTable ConvertToLua_GetDisplayRosterRequest   (LuaThread *lua, const Blaze::Franchise::GetDisplayRosterRequest &value);
void     ConvertFromLua_GetDisplayRosterRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetDisplayRosterRequest &value);

// GetDisplayRosterByAthleteRequest
LuaTable ConvertToLua_GetDisplayRosterByAthleteRequest   (LuaThread *lua, const Blaze::Franchise::GetDisplayRosterByAthleteRequest &value);
void     ConvertFromLua_GetDisplayRosterByAthleteRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetDisplayRosterByAthleteRequest &value);

// GetDisplayAthleteResponse
LuaTable ConvertToLua_GetDisplayAthleteResponse   (LuaThread *lua, const Blaze::Franchise::GetDisplayAthleteResponse &value);
void     ConvertFromLua_GetDisplayAthleteResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::GetDisplayAthleteResponse &value);

// GetDisplayAthleteRequest
LuaTable ConvertToLua_GetDisplayAthleteRequest   (LuaThread *lua, const Blaze::Franchise::GetDisplayAthleteRequest &value);
void     ConvertFromLua_GetDisplayAthleteRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetDisplayAthleteRequest &value);

// GetDepthChartResponse
LuaTable ConvertToLua_GetDepthChartResponse   (LuaThread *lua, const Blaze::Franchise::GetDepthChartResponse &value);
void     ConvertFromLua_GetDepthChartResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::GetDepthChartResponse &value);

// GetDepthChartRequest
LuaTable ConvertToLua_GetDepthChartRequest   (LuaThread *lua, const Blaze::Franchise::GetDepthChartRequest &value);
void     ConvertFromLua_GetDepthChartRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetDepthChartRequest &value);

// SetDepthChartRequest
LuaTable ConvertToLua_SetDepthChartRequest   (LuaThread *lua, const Blaze::Franchise::SetDepthChartRequest &value);
void     ConvertFromLua_SetDepthChartRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::SetDepthChartRequest &value);

// GenerateDepthChartRequest
LuaTable ConvertToLua_GenerateDepthChartRequest   (LuaThread *lua, const Blaze::Franchise::GenerateDepthChartRequest &value);
void     ConvertFromLua_GenerateDepthChartRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GenerateDepthChartRequest &value);

// RegularGameInfo
LuaTable ConvertToLua_RegularGameInfo   (LuaThread *lua, const Blaze::Franchise::RegularGameInfo &value);
void     ConvertFromLua_RegularGameInfo (LuaThread *lua, LuaTable table, Blaze::Franchise::RegularGameInfo &value);

// PlayoffGameInfo
LuaTable ConvertToLua_PlayoffGameInfo   (LuaThread *lua, const Blaze::Franchise::PlayoffGameInfo &value);
void     ConvertFromLua_PlayoffGameInfo (LuaThread *lua, LuaTable table, Blaze::Franchise::PlayoffGameInfo &value);

// GetRegularScheduleResponse
LuaTable ConvertToLua_GetRegularScheduleResponse   (LuaThread *lua, const Blaze::Franchise::GetRegularScheduleResponse &value);
void     ConvertFromLua_GetRegularScheduleResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::GetRegularScheduleResponse &value);

// GetRegularScheduleRequest
LuaTable ConvertToLua_GetRegularScheduleRequest   (LuaThread *lua, const Blaze::Franchise::GetRegularScheduleRequest &value);
void     ConvertFromLua_GetRegularScheduleRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetRegularScheduleRequest &value);

// GetPlayoffScheduleResponse
LuaTable ConvertToLua_GetPlayoffScheduleResponse   (LuaThread *lua, const Blaze::Franchise::GetPlayoffScheduleResponse &value);
void     ConvertFromLua_GetPlayoffScheduleResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::GetPlayoffScheduleResponse &value);

// GetPlayoffScheduleRequest
LuaTable ConvertToLua_GetPlayoffScheduleRequest   (LuaThread *lua, const Blaze::Franchise::GetPlayoffScheduleRequest &value);
void     ConvertFromLua_GetPlayoffScheduleRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetPlayoffScheduleRequest &value);

// Trade
LuaTable ConvertToLua_Trade   (LuaThread *lua, const Blaze::Franchise::Trade &value);
void     ConvertFromLua_Trade (LuaThread *lua, LuaTable table, Blaze::Franchise::Trade &value);

// ProposeTradeRequest
LuaTable ConvertToLua_ProposeTradeRequest   (LuaThread *lua, const Blaze::Franchise::ProposeTradeRequest &value);
void     ConvertFromLua_ProposeTradeRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::ProposeTradeRequest &value);

// GetTradesRequest
LuaTable ConvertToLua_GetTradesRequest   (LuaThread *lua, const Blaze::Franchise::GetTradesRequest &value);
void     ConvertFromLua_GetTradesRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetTradesRequest &value);

// GetCpuTradesRequest
LuaTable ConvertToLua_GetCpuTradesRequest   (LuaThread *lua, const Blaze::Franchise::GetCpuTradesRequest &value);
void     ConvertFromLua_GetCpuTradesRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetCpuTradesRequest &value);

// InvalidTradeError
LuaTable ConvertToLua_InvalidTradeError   (LuaThread *lua, const Blaze::Franchise::InvalidTradeError &value);
void     ConvertFromLua_InvalidTradeError (LuaThread *lua, LuaTable table, Blaze::Franchise::InvalidTradeError &value);

// GetTradesResponse
LuaTable ConvertToLua_GetTradesResponse   (LuaThread *lua, const Blaze::Franchise::GetTradesResponse &value);
void     ConvertFromLua_GetTradesResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::GetTradesResponse &value);

// ProcessCpuTradesRequest
LuaTable ConvertToLua_ProcessCpuTradesRequest   (LuaThread *lua, const Blaze::Franchise::ProcessCpuTradesRequest &value);
void     ConvertFromLua_ProcessCpuTradesRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::ProcessCpuTradesRequest &value);

// ProcessTradeRequest
LuaTable ConvertToLua_ProcessTradeRequest   (LuaThread *lua, const Blaze::Franchise::ProcessTradeRequest &value);
void     ConvertFromLua_ProcessTradeRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::ProcessTradeRequest &value);

// FranchiseCacheEntry
LuaTable ConvertToLua_FranchiseCacheEntry   (LuaThread *lua, const Blaze::Franchise::FranchiseCacheEntry &value);
void     ConvertFromLua_FranchiseCacheEntry (LuaThread *lua, LuaTable table, Blaze::Franchise::FranchiseCacheEntry &value);

// InvalidateFranchiseCacheEntryRequest
LuaTable ConvertToLua_InvalidateFranchiseCacheEntryRequest   (LuaThread *lua, const Blaze::Franchise::InvalidateFranchiseCacheEntryRequest &value);
void     ConvertFromLua_InvalidateFranchiseCacheEntryRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::InvalidateFranchiseCacheEntryRequest &value);

// AdvanceFranchiseRequest
LuaTable ConvertToLua_AdvanceFranchiseRequest   (LuaThread *lua, const Blaze::Franchise::AdvanceFranchiseRequest &value);
void     ConvertFromLua_AdvanceFranchiseRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::AdvanceFranchiseRequest &value);

// SimSeasonRequest
LuaTable ConvertToLua_SimSeasonRequest   (LuaThread *lua, const Blaze::Franchise::SimSeasonRequest &value);
void     ConvertFromLua_SimSeasonRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::SimSeasonRequest &value);

// AthleteProgressRequest
LuaTable ConvertToLua_AthleteProgressRequest   (LuaThread *lua, const Blaze::Franchise::AthleteProgressRequest &value);
void     ConvertFromLua_AthleteProgressRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::AthleteProgressRequest &value);

// RawDataFilter
LuaTable ConvertToLua_RawDataFilter   (LuaThread *lua, const Blaze::Franchise::RawDataFilter &value);
void     ConvertFromLua_RawDataFilter (LuaThread *lua, LuaTable table, Blaze::Franchise::RawDataFilter &value);

// RawDataFormat
LuaTable ConvertToLua_RawDataFormat   (LuaThread *lua, const Blaze::Franchise::RawDataFormat &value);
void     ConvertFromLua_RawDataFormat (LuaThread *lua, LuaTable table, Blaze::Franchise::RawDataFormat &value);

// GetRawDataRequest
LuaTable ConvertToLua_GetRawDataRequest   (LuaThread *lua, const Blaze::Franchise::GetRawDataRequest &value);
void     ConvertFromLua_GetRawDataRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetRawDataRequest &value);

// GetRawDataResponse
LuaTable ConvertToLua_GetRawDataResponse   (LuaThread *lua, const Blaze::Franchise::GetRawDataResponse &value);
void     ConvertFromLua_GetRawDataResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::GetRawDataResponse &value);

// SignAthleteRequest
LuaTable ConvertToLua_SignAthleteRequest   (LuaThread *lua, const Blaze::Franchise::SignAthleteRequest &value);
void     ConvertFromLua_SignAthleteRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::SignAthleteRequest &value);

// ReleaseAthleteRequest
LuaTable ConvertToLua_ReleaseAthleteRequest   (LuaThread *lua, const Blaze::Franchise::ReleaseAthleteRequest &value);
void     ConvertFromLua_ReleaseAthleteRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::ReleaseAthleteRequest &value);

// GetNumTeamInjuriesRequest
LuaTable ConvertToLua_GetNumTeamInjuriesRequest   (LuaThread *lua, const Blaze::Franchise::GetNumTeamInjuriesRequest &value);
void     ConvertFromLua_GetNumTeamInjuriesRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetNumTeamInjuriesRequest &value);

// GetNumTeamInjuriesResponse
LuaTable ConvertToLua_GetNumTeamInjuriesResponse   (LuaThread *lua, const Blaze::Franchise::GetNumTeamInjuriesResponse &value);
void     ConvertFromLua_GetNumTeamInjuriesResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::GetNumTeamInjuriesResponse &value);

// AthleteInjury
LuaTable ConvertToLua_AthleteInjury   (LuaThread *lua, const Blaze::Franchise::AthleteInjury &value);
void     ConvertFromLua_AthleteInjury (LuaThread *lua, LuaTable table, Blaze::Franchise::AthleteInjury &value);

// GetInjuriesByTeamRequest
LuaTable ConvertToLua_GetInjuriesByTeamRequest   (LuaThread *lua, const Blaze::Franchise::GetInjuriesByTeamRequest &value);
void     ConvertFromLua_GetInjuriesByTeamRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetInjuriesByTeamRequest &value);

// GetInjuriesByTeamResponse
LuaTable ConvertToLua_GetInjuriesByTeamResponse   (LuaThread *lua, const Blaze::Franchise::GetInjuriesByTeamResponse &value);
void     ConvertFromLua_GetInjuriesByTeamResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::GetInjuriesByTeamResponse &value);

// TeamGameplayInformation
LuaTable ConvertToLua_TeamGameplayInformation   (LuaThread *lua, const Blaze::Franchise::TeamGameplayInformation &value);
void     ConvertFromLua_TeamGameplayInformation (LuaThread *lua, LuaTable table, Blaze::Franchise::TeamGameplayInformation &value);

// GetGameplayInformationRequest
LuaTable ConvertToLua_GetGameplayInformationRequest   (LuaThread *lua, const Blaze::Franchise::GetGameplayInformationRequest &value);
void     ConvertFromLua_GetGameplayInformationRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetGameplayInformationRequest &value);

// GetGameplayInformationResponse
LuaTable ConvertToLua_GetGameplayInformationResponse   (LuaThread *lua, const Blaze::Franchise::GetGameplayInformationResponse &value);
void     ConvertFromLua_GetGameplayInformationResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::GetGameplayInformationResponse &value);

// RetiredAthleteInfo
LuaTable ConvertToLua_RetiredAthleteInfo   (LuaThread *lua, const Blaze::Franchise::RetiredAthleteInfo &value);
void     ConvertFromLua_RetiredAthleteInfo (LuaThread *lua, LuaTable table, Blaze::Franchise::RetiredAthleteInfo &value);

// GetRetirementsRequest
LuaTable ConvertToLua_GetRetirementsRequest   (LuaThread *lua, const Blaze::Franchise::GetRetirementsRequest &value);
void     ConvertFromLua_GetRetirementsRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetRetirementsRequest &value);

// GetRetirementsResponse
LuaTable ConvertToLua_GetRetirementsResponse   (LuaThread *lua, const Blaze::Franchise::GetRetirementsResponse &value);
void     ConvertFromLua_GetRetirementsResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::GetRetirementsResponse &value);

// GameBoxScore
LuaTable ConvertToLua_GameBoxScore   (LuaThread *lua, const Blaze::Franchise::GameBoxScore &value);
void     ConvertFromLua_GameBoxScore (LuaThread *lua, LuaTable table, Blaze::Franchise::GameBoxScore &value);

// GetGameBoxScoreByGameRequest
LuaTable ConvertToLua_GetGameBoxScoreByGameRequest   (LuaThread *lua, const Blaze::Franchise::GetGameBoxScoreByGameRequest &value);
void     ConvertFromLua_GetGameBoxScoreByGameRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetGameBoxScoreByGameRequest &value);

// GetGameBoxScoresByWeekRequest
LuaTable ConvertToLua_GetGameBoxScoresByWeekRequest   (LuaThread *lua, const Blaze::Franchise::GetGameBoxScoresByWeekRequest &value);
void     ConvertFromLua_GetGameBoxScoresByWeekRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetGameBoxScoresByWeekRequest &value);

// GetGameBoxScoresByTeamRequest
LuaTable ConvertToLua_GetGameBoxScoresByTeamRequest   (LuaThread *lua, const Blaze::Franchise::GetGameBoxScoresByTeamRequest &value);
void     ConvertFromLua_GetGameBoxScoresByTeamRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetGameBoxScoresByTeamRequest &value);

// GetGameBoxScoresByWeekResponse
LuaTable ConvertToLua_GetGameBoxScoresByWeekResponse   (LuaThread *lua, const Blaze::Franchise::GetGameBoxScoresByWeekResponse &value);
void     ConvertFromLua_GetGameBoxScoresByWeekResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::GetGameBoxScoresByWeekResponse &value);

// GetGameBoxScoresByTeamResponse
LuaTable ConvertToLua_GetGameBoxScoresByTeamResponse   (LuaThread *lua, const Blaze::Franchise::GetGameBoxScoresByTeamResponse &value);
void     ConvertFromLua_GetGameBoxScoresByTeamResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::GetGameBoxScoresByTeamResponse &value);

// ScoreDescription
LuaTable ConvertToLua_ScoreDescription   (LuaThread *lua, const Blaze::Franchise::ScoreDescription &value);
void     ConvertFromLua_ScoreDescription (LuaThread *lua, LuaTable table, Blaze::Franchise::ScoreDescription &value);

// GetScoringSummaryRequest
LuaTable ConvertToLua_GetScoringSummaryRequest   (LuaThread *lua, const Blaze::Franchise::GetScoringSummaryRequest &value);
void     ConvertFromLua_GetScoringSummaryRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetScoringSummaryRequest &value);

// GetScoringSummaryResponse
LuaTable ConvertToLua_GetScoringSummaryResponse   (LuaThread *lua, const Blaze::Franchise::GetScoringSummaryResponse &value);
void     ConvertFromLua_GetScoringSummaryResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::GetScoringSummaryResponse &value);

// SubmitScoringSummaryRequest
LuaTable ConvertToLua_SubmitScoringSummaryRequest   (LuaThread *lua, const Blaze::Franchise::SubmitScoringSummaryRequest &value);
void     ConvertFromLua_SubmitScoringSummaryRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::SubmitScoringSummaryRequest &value);

// TeamStats
LuaTable ConvertToLua_TeamStats   (LuaThread *lua, const Blaze::Franchise::TeamStats &value);
void     ConvertFromLua_TeamStats (LuaThread *lua, LuaTable table, Blaze::Franchise::TeamStats &value);

// GetTeamStatsByGameRequest
LuaTable ConvertToLua_GetTeamStatsByGameRequest   (LuaThread *lua, const Blaze::Franchise::GetTeamStatsByGameRequest &value);
void     ConvertFromLua_GetTeamStatsByGameRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetTeamStatsByGameRequest &value);

// GetTeamStatsByGameResponse
LuaTable ConvertToLua_GetTeamStatsByGameResponse   (LuaThread *lua, const Blaze::Franchise::GetTeamStatsByGameResponse &value);
void     ConvertFromLua_GetTeamStatsByGameResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::GetTeamStatsByGameResponse &value);

// SubmitTeamGameStatsRequest
LuaTable ConvertToLua_SubmitTeamGameStatsRequest   (LuaThread *lua, const Blaze::Franchise::SubmitTeamGameStatsRequest &value);
void     ConvertFromLua_SubmitTeamGameStatsRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::SubmitTeamGameStatsRequest &value);

// PassingStats
LuaTable ConvertToLua_PassingStats   (LuaThread *lua, const Blaze::Franchise::PassingStats &value);
void     ConvertFromLua_PassingStats (LuaThread *lua, LuaTable table, Blaze::Franchise::PassingStats &value);

// RushingStats
LuaTable ConvertToLua_RushingStats   (LuaThread *lua, const Blaze::Franchise::RushingStats &value);
void     ConvertFromLua_RushingStats (LuaThread *lua, LuaTable table, Blaze::Franchise::RushingStats &value);

// ReceivingStats
LuaTable ConvertToLua_ReceivingStats   (LuaThread *lua, const Blaze::Franchise::ReceivingStats &value);
void     ConvertFromLua_ReceivingStats (LuaThread *lua, LuaTable table, Blaze::Franchise::ReceivingStats &value);

// BlockingStats
LuaTable ConvertToLua_BlockingStats   (LuaThread *lua, const Blaze::Franchise::BlockingStats &value);
void     ConvertFromLua_BlockingStats (LuaThread *lua, LuaTable table, Blaze::Franchise::BlockingStats &value);

// KickingStats
LuaTable ConvertToLua_KickingStats   (LuaThread *lua, const Blaze::Franchise::KickingStats &value);
void     ConvertFromLua_KickingStats (LuaThread *lua, LuaTable table, Blaze::Franchise::KickingStats &value);

// PuntingStats
LuaTable ConvertToLua_PuntingStats   (LuaThread *lua, const Blaze::Franchise::PuntingStats &value);
void     ConvertFromLua_PuntingStats (LuaThread *lua, LuaTable table, Blaze::Franchise::PuntingStats &value);

// KickoffReturnStats
LuaTable ConvertToLua_KickoffReturnStats   (LuaThread *lua, const Blaze::Franchise::KickoffReturnStats &value);
void     ConvertFromLua_KickoffReturnStats (LuaThread *lua, LuaTable table, Blaze::Franchise::KickoffReturnStats &value);

// PuntReturnStats
LuaTable ConvertToLua_PuntReturnStats   (LuaThread *lua, const Blaze::Franchise::PuntReturnStats &value);
void     ConvertFromLua_PuntReturnStats (LuaThread *lua, LuaTable table, Blaze::Franchise::PuntReturnStats &value);

// DefenseStats
LuaTable ConvertToLua_DefenseStats   (LuaThread *lua, const Blaze::Franchise::DefenseStats &value);
void     ConvertFromLua_DefenseStats (LuaThread *lua, LuaTable table, Blaze::Franchise::DefenseStats &value);

// AthleteStatsByTeam
LuaTable ConvertToLua_AthleteStatsByTeam   (LuaThread *lua, const Blaze::Franchise::AthleteStatsByTeam &value);
void     ConvertFromLua_AthleteStatsByTeam (LuaThread *lua, LuaTable table, Blaze::Franchise::AthleteStatsByTeam &value);

// GetAthleteStatsByGameRequest
LuaTable ConvertToLua_GetAthleteStatsByGameRequest   (LuaThread *lua, const Blaze::Franchise::GetAthleteStatsByGameRequest &value);
void     ConvertFromLua_GetAthleteStatsByGameRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetAthleteStatsByGameRequest &value);

// GetAthleteStatsByGameResponse
LuaTable ConvertToLua_GetAthleteStatsByGameResponse   (LuaThread *lua, const Blaze::Franchise::GetAthleteStatsByGameResponse &value);
void     ConvertFromLua_GetAthleteStatsByGameResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::GetAthleteStatsByGameResponse &value);

// SubmitAthleteGameStatsRequest
LuaTable ConvertToLua_SubmitAthleteGameStatsRequest   (LuaThread *lua, const Blaze::Franchise::SubmitAthleteGameStatsRequest &value);
void     ConvertFromLua_SubmitAthleteGameStatsRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::SubmitAthleteGameStatsRequest &value);

// GetGameStatReportRequest
LuaTable ConvertToLua_GetGameStatReportRequest   (LuaThread *lua, const Blaze::Franchise::GetGameStatReportRequest &value);
void     ConvertFromLua_GetGameStatReportRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetGameStatReportRequest &value);

// GetGameStatReportResponse
LuaTable ConvertToLua_GetGameStatReportResponse   (LuaThread *lua, const Blaze::Franchise::GetGameStatReportResponse &value);
void     ConvertFromLua_GetGameStatReportResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::GetGameStatReportResponse &value);

// PostNewsRequest
LuaTable ConvertToLua_PostNewsRequest   (LuaThread *lua, const Blaze::Franchise::PostNewsRequest &value);
void     ConvertFromLua_PostNewsRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::PostNewsRequest &value);

// GetNewsRequest
LuaTable ConvertToLua_GetNewsRequest   (LuaThread *lua, const Blaze::Franchise::GetNewsRequest &value);
void     ConvertFromLua_GetNewsRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetNewsRequest &value);

// GetNewsResponse
LuaTable ConvertToLua_GetNewsResponse   (LuaThread *lua, const Blaze::Franchise::GetNewsResponse &value);
void     ConvertFromLua_GetNewsResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::GetNewsResponse &value);

// CheckFranchiseStateRequest
LuaTable ConvertToLua_CheckFranchiseStateRequest   (LuaThread *lua, const Blaze::Franchise::CheckFranchiseStateRequest &value);
void     ConvertFromLua_CheckFranchiseStateRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::CheckFranchiseStateRequest &value);

// GetFranchiseRankRequest
LuaTable ConvertToLua_GetFranchiseRankRequest   (LuaThread *lua, const Blaze::Franchise::GetFranchiseRankRequest &value);
void     ConvertFromLua_GetFranchiseRankRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetFranchiseRankRequest &value);

// FranchiseRank
LuaTable ConvertToLua_FranchiseRank   (LuaThread *lua, const Blaze::Franchise::FranchiseRank &value);
void     ConvertFromLua_FranchiseRank (LuaThread *lua, LuaTable table, Blaze::Franchise::FranchiseRank &value);

// MemberSummary
LuaTable ConvertToLua_MemberSummary   (LuaThread *lua, const Blaze::Franchise::MemberSummary &value);
void     ConvertFromLua_MemberSummary (LuaThread *lua, LuaTable table, Blaze::Franchise::MemberSummary &value);

// JoinDraftRequest
LuaTable ConvertToLua_JoinDraftRequest   (LuaThread *lua, const Blaze::Franchise::JoinDraftRequest &value);
void     ConvertFromLua_JoinDraftRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::JoinDraftRequest &value);

// DraftTeam
LuaTable ConvertToLua_DraftTeam   (LuaThread *lua, const Blaze::Franchise::DraftTeam &value);
void     ConvertFromLua_DraftTeam (LuaThread *lua, LuaTable table, Blaze::Franchise::DraftTeam &value);

// JoinDraftResponse
LuaTable ConvertToLua_JoinDraftResponse   (LuaThread *lua, const Blaze::Franchise::JoinDraftResponse &value);
void     ConvertFromLua_JoinDraftResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::JoinDraftResponse &value);

// JoinDraftMasterRequest
LuaTable ConvertToLua_JoinDraftMasterRequest   (LuaThread *lua, const Blaze::Franchise::JoinDraftMasterRequest &value);
void     ConvertFromLua_JoinDraftMasterRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::JoinDraftMasterRequest &value);

// LeaveDraftRequest
LuaTable ConvertToLua_LeaveDraftRequest   (LuaThread *lua, const Blaze::Franchise::LeaveDraftRequest &value);
void     ConvertFromLua_LeaveDraftRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::LeaveDraftRequest &value);

// BeginDraftRequest
LuaTable ConvertToLua_BeginDraftRequest   (LuaThread *lua, const Blaze::Franchise::BeginDraftRequest &value);
void     ConvertFromLua_BeginDraftRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::BeginDraftRequest &value);

// PauseDraftRequest
LuaTable ConvertToLua_PauseDraftRequest   (LuaThread *lua, const Blaze::Franchise::PauseDraftRequest &value);
void     ConvertFromLua_PauseDraftRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::PauseDraftRequest &value);

// DraftAthleteRequest
LuaTable ConvertToLua_DraftAthleteRequest   (LuaThread *lua, const Blaze::Franchise::DraftAthleteRequest &value);
void     ConvertFromLua_DraftAthleteRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::DraftAthleteRequest &value);

// GetDraftOrderRequest
LuaTable ConvertToLua_GetDraftOrderRequest   (LuaThread *lua, const Blaze::Franchise::GetDraftOrderRequest &value);
void     ConvertFromLua_GetDraftOrderRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetDraftOrderRequest &value);

// GetDraftOrderResponse
LuaTable ConvertToLua_GetDraftOrderResponse   (LuaThread *lua, const Blaze::Franchise::GetDraftOrderResponse &value);
void     ConvertFromLua_GetDraftOrderResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::GetDraftOrderResponse &value);

// SendDraftChatRequest
LuaTable ConvertToLua_SendDraftChatRequest   (LuaThread *lua, const Blaze::Franchise::SendDraftChatRequest &value);
void     ConvertFromLua_SendDraftChatRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::SendDraftChatRequest &value);

// GetDraftHistoryRequest
LuaTable ConvertToLua_GetDraftHistoryRequest   (LuaThread *lua, const Blaze::Franchise::GetDraftHistoryRequest &value);
void     ConvertFromLua_GetDraftHistoryRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetDraftHistoryRequest &value);

// DraftPick
LuaTable ConvertToLua_DraftPick   (LuaThread *lua, const Blaze::Franchise::DraftPick &value);
void     ConvertFromLua_DraftPick (LuaThread *lua, LuaTable table, Blaze::Franchise::DraftPick &value);

// GetDraftHistoryResponse
LuaTable ConvertToLua_GetDraftHistoryResponse   (LuaThread *lua, const Blaze::Franchise::GetDraftHistoryResponse &value);
void     ConvertFromLua_GetDraftHistoryResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::GetDraftHistoryResponse &value);

// CheckDraftRequest
LuaTable ConvertToLua_CheckDraftRequest   (LuaThread *lua, const Blaze::Franchise::CheckDraftRequest &value);
void     ConvertFromLua_CheckDraftRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::CheckDraftRequest &value);

// CheckDraftResponse
LuaTable ConvertToLua_CheckDraftResponse   (LuaThread *lua, const Blaze::Franchise::CheckDraftResponse &value);
void     ConvertFromLua_CheckDraftResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::CheckDraftResponse &value);

// DraftStatusNotification
LuaTable ConvertToLua_DraftStatusNotification   (LuaThread *lua, const Blaze::Franchise::DraftStatusNotification &value);
void     ConvertFromLua_DraftStatusNotification (LuaThread *lua, LuaTable table, Blaze::Franchise::DraftStatusNotification &value);

// DraftSelectionNotification
LuaTable ConvertToLua_DraftSelectionNotification   (LuaThread *lua, const Blaze::Franchise::DraftSelectionNotification &value);
void     ConvertFromLua_DraftSelectionNotification (LuaThread *lua, LuaTable table, Blaze::Franchise::DraftSelectionNotification &value);

// DraftMemberJoinedNotification
LuaTable ConvertToLua_DraftMemberJoinedNotification   (LuaThread *lua, const Blaze::Franchise::DraftMemberJoinedNotification &value);
void     ConvertFromLua_DraftMemberJoinedNotification (LuaThread *lua, LuaTable table, Blaze::Franchise::DraftMemberJoinedNotification &value);

// DraftMemberLeftNotification
LuaTable ConvertToLua_DraftMemberLeftNotification   (LuaThread *lua, const Blaze::Franchise::DraftMemberLeftNotification &value);
void     ConvertFromLua_DraftMemberLeftNotification (LuaThread *lua, LuaTable table, Blaze::Franchise::DraftMemberLeftNotification &value);

// DraftChatNotification
LuaTable ConvertToLua_DraftChatNotification   (LuaThread *lua, const Blaze::Franchise::DraftChatNotification &value);
void     ConvertFromLua_DraftChatNotification (LuaThread *lua, LuaTable table, Blaze::Franchise::DraftChatNotification &value);

// DraftNotification
LuaTable ConvertToLua_DraftNotification   (LuaThread *lua, const Blaze::Franchise::DraftNotification &value);
void     ConvertFromLua_DraftNotification (LuaThread *lua, LuaTable table, Blaze::Franchise::DraftNotification &value);

// DraftNotificationWrapper
LuaTable ConvertToLua_DraftNotificationWrapper   (LuaThread *lua, const Blaze::Franchise::DraftNotificationWrapper &value);
void     ConvertFromLua_DraftNotificationWrapper (LuaThread *lua, LuaTable table, Blaze::Franchise::DraftNotificationWrapper &value);

// DraftCompleteNotification
LuaTable ConvertToLua_DraftCompleteNotification   (LuaThread *lua, const Blaze::Franchise::DraftCompleteNotification &value);
void     ConvertFromLua_DraftCompleteNotification (LuaThread *lua, LuaTable table, Blaze::Franchise::DraftCompleteNotification &value);

// PollDraftRequest
LuaTable ConvertToLua_PollDraftRequest   (LuaThread *lua, const Blaze::Franchise::PollDraftRequest &value);
void     ConvertFromLua_PollDraftRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::PollDraftRequest &value);

// PollDraftResponse
LuaTable ConvertToLua_PollDraftResponse   (LuaThread *lua, const Blaze::Franchise::PollDraftResponse &value);
void     ConvertFromLua_PollDraftResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::PollDraftResponse &value);

// GetTopFranchisesRequest
LuaTable ConvertToLua_GetTopFranchisesRequest   (LuaThread *lua, const Blaze::Franchise::GetTopFranchisesRequest &value);
void     ConvertFromLua_GetTopFranchisesRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetTopFranchisesRequest &value);

// GetTopFranchisesResponse
LuaTable ConvertToLua_GetTopFranchisesResponse   (LuaThread *lua, const Blaze::Franchise::GetTopFranchisesResponse &value);
void     ConvertFromLua_GetTopFranchisesResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::GetTopFranchisesResponse &value);

// SuperbowlResult
LuaTable ConvertToLua_SuperbowlResult   (LuaThread *lua, const Blaze::Franchise::SuperbowlResult &value);
void     ConvertFromLua_SuperbowlResult (LuaThread *lua, LuaTable table, Blaze::Franchise::SuperbowlResult &value);

// GetSuperbowlsRequest
LuaTable ConvertToLua_GetSuperbowlsRequest   (LuaThread *lua, const Blaze::Franchise::GetSuperbowlsRequest &value);
void     ConvertFromLua_GetSuperbowlsRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::GetSuperbowlsRequest &value);

// GetSuperbowlsResponse
LuaTable ConvertToLua_GetSuperbowlsResponse   (LuaThread *lua, const Blaze::Franchise::GetSuperbowlsResponse &value);
void     ConvertFromLua_GetSuperbowlsResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::GetSuperbowlsResponse &value);

// ValidateRostersRequest
LuaTable ConvertToLua_ValidateRostersRequest   (LuaThread *lua, const Blaze::Franchise::ValidateRostersRequest &value);
void     ConvertFromLua_ValidateRostersRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::ValidateRostersRequest &value);

// ValidateDepthChartsRequest
LuaTable ConvertToLua_ValidateDepthChartsRequest   (LuaThread *lua, const Blaze::Franchise::ValidateDepthChartsRequest &value);
void     ConvertFromLua_ValidateDepthChartsRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::ValidateDepthChartsRequest &value);

// SubmitFranchiseGameStatsRequest
LuaTable ConvertToLua_SubmitFranchiseGameStatsRequest   (LuaThread *lua, const Blaze::Franchise::SubmitFranchiseGameStatsRequest &value);
void     ConvertFromLua_SubmitFranchiseGameStatsRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::SubmitFranchiseGameStatsRequest &value);

// SubmitAntiCheatInfoRequest
LuaTable ConvertToLua_SubmitAntiCheatInfoRequest   (LuaThread *lua, const Blaze::Franchise::SubmitAntiCheatInfoRequest &value);
void     ConvertFromLua_SubmitAntiCheatInfoRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::SubmitAntiCheatInfoRequest &value);

// ValidateMatchInfoRequest
LuaTable ConvertToLua_ValidateMatchInfoRequest   (LuaThread *lua, const Blaze::Franchise::ValidateMatchInfoRequest &value);
void     ConvertFromLua_ValidateMatchInfoRequest (LuaThread *lua, LuaTable table, Blaze::Franchise::ValidateMatchInfoRequest &value);

// GetServerSettingsResponse
LuaTable ConvertToLua_GetServerSettingsResponse   (LuaThread *lua, const Blaze::Franchise::GetServerSettingsResponse &value);
void     ConvertFromLua_GetServerSettingsResponse (LuaThread *lua, LuaTable table, Blaze::Franchise::GetServerSettingsResponse &value);


} // Stress
} // Blaze

#endif // C__DEV_BLAZE_GAMES_MADDEN_2010_NG_TRUNK_COMPONENT_FRANCHISE_GEN_FRANCHISE_STRESS_H

