#include "PlaceNameGenerator.h"

#include <stdio.h>
#include <string.h>

static const char *placeNames[] =
{
    ".Abaddon",
    ".Agony",
    ".Alcazar",
    ".Gehenna",
    ".Hades",
    ".Heaven",
    ".Hell",
    ".Hellfire",
    ".Home",
    ".Limbo",
    ".Pandemonium",
    ".Perdition",
    ".Purgatory",
    ".Space",
    ".Suffering",
    "Abbey",
    "Abode",
    "Abyss",
    "Acropolis",
    "Affliction",
    "Afterlife",
    "Aftertime",
    "Afterworld",
    "Alcove",
    "Ambush",
    "Anguish",
    "Antechamber",
    "Ascension",
    "Asylum",
    "Balcony",
    "Barrier",
    "Bastion",
    "Beyond",
    "Black-Hole",
    "Bottomless-Pit",
    "Box",
    "Breach",
    "Break",
    "Bridge",
    "Brig",
    "Burrow",
    "Cage",
    "Camp",
    "Castellum",
    "Castle",
    "Cathedral",
    "Cave",
    "Cavity",
    "Cell",
    "Chamber",
    "Chapel",
    "Chapter-House",
    "Chest",
    "Churchyard",
    "Citadel",
    "Cloister",
    "Closure",
    "Confinement",
    "Convent",
    "Coop",
    "Corner",
    "Corral",
    "Cortege",
    "Court",
    "Courtyard",
    "Crack",
    "Cranny",
    "Crevice",
    "Crib",
    "Crypt",
    "Cult",
    "Den",
    "Donjon",
    "Dump",
    "Dungeon",
    "Dwelling",
    "Encampment",
    "Enclosure",
    "Everlasting-Fire",
    "Fasthold",
    "Fence",
    "Fold",
    "Fort",
    "Fortification",
    "Fortress",
    "Friary",
    "Gallery",
    "Garden",
    "Gorge",
    "Grave",
    "Graveyard",
    "Grounds",
    "Guardhouse",
    "Hall",
    "Hatch",
    "Haven",
    "Hearth",
    "Hedge",
    "Hereafter",
    "Hermitage",
    "Hold",
    "Hole",
    "Hollow",
    "House",
    "Household",
    "Hutch",
    "Inferno",
    "Inside",
    "Interstice",
    "Jail",
    "Keep",
    "Lamasery",
    "Lockup",
    "Lowerworld",
    "Manor",
    "Mansion",
    "Monastery",
    "Mouth",
    "Necropolis",
    "Netherworld",
    "Niche",
    "Nightmare",
    "Nook",
    "Opening",
    "Otherworld",
    "Oubliette",
    "Outlet",
    "Overlook",
    "Palace",
    "Pale",
    "Park",
    "Patch",
    "Peel",
    "Pen",
    "Penitentiary",
    "Perforation",
    "Pit",
    "Place-of-Torment",
    "Plot",
    "Pocket",
    "Portal",
    "Portico",
    "Priory",
    "Prison",
    "Rack",
    "Recess",
    "Redoubt",
    "Region",
    "Retinue",
    "Retreat",
    "Rift",
    "Rincon",
    "River",
    "Room",
    "Roost",
    "Rupture",
    "Safehold",
    "Sanctuary",
    "Seat",
    "Settlement",
    "Stall",
    "Stockade",
    "Stronghold",
    "Sty",
    "Suite",
    "Terrace",
    "Torment",
    "Torture-Chamber",
    "Tower",
    "Underworld",
    "Vault",
    "Veranda",
    "Walk",
    "Wall",
    "Waypoint",
    "Yard",
    "Zone",
/*
"Aconite",
"Alder",
"Black Alder",
"Common Alder",
"False Alder",
"Gray Alder",
"Speckled Alder",
"Striped Alder",
"White Alder",
"Ambrosia",
"Tall Ambrosia",
"Amy Root",
"Apple",
"Osage Apple",
"Apple of Sodom",
"Arfaj",
"Arrowwood",
"Indian Arrowwood",
"Ash",
"Black Ash",
"Blue Ash",
"Cane Ash",
"Green Ash",
"Maple Ash",
"Red Ash",
"River Ash",
"Swamp Ash",
"White Ash",
"Water Ash",
"Azolla",
"Carolina Azolla",
"Bearberry",
"Bear Corn",
"Bindweed",
"Blue Bindweed",
"Bird's Nest",
"Bird's Nest Plant",
"Birch",
"Black Birch",
"Bolean Birch",
"Canoe Birch",
"Cherry Birch",
"European Weeping Birch",
"European White Birch",
"Gray Birch",
"Mahogany Birch",
"Paper Birch",
"Red Birch",
"River Birch",
"Silver Birch",
"Spice Birch",
"Sweet Birch",
"Water Birch",
"Weeping Birch",
"White Birch",
"Yellow Birch",
"Bittercress",
"Hairy Bittercress",
"Bittersweet",
"Trailing Bittersweet",
"Bitterweed",
"Blackberry",
"Hispid Swamp Blackberry",
"Pennsylvania Blackberry",
"Running Swamp Blackberry",
"Black Cap",
"Black",
"Blackhaw",
"Blackiehead",
"Black",
"Blue",
"Bow",
"Box",
"False Box",
"Boxelder",
"Boxwood",
"False Boxwood",
"Brier",
"Sand Brier",
"Brittlebush",
"Broadleaf",
"Brown Betty",
"Brown",
"Buffalo Weed",
"Butterfly Flower",
"Butterfly Weed",
"Cabbage",
"Clumpfoot Cabbage",
"Meadow Cabbage",
"Skunk Cabbage",
"Swamp Cabbage",
"Canada Root",
"Cancer Jalap",
"Carrot",
"Wild Carrot",
"Carrot Weed",
"Cart Track Plant",
"Cherry",
"Black Cherry",
"Cabinet Cherry",
"Rum Cherry",
"Whiskey Cherry",
"Wild Cherry",
"Wild Black Cherry",
"Chigger Flower",
"Chrysanthemum",
"Coakum",
"Colic Weed",
"Collard",
"Colwort",
"Hare's Colwort",
"Coneflower",
"Brilliant Coneflower",
"Cutleaf Coneflower",
"Eastern Coneflower",
"Green",
"Orange Coneflower",
"Tall Coneflower",
"Thin",
"Three",
"Cornel",
"Blueberry Cornel",
"Silky Cornel",
"White Cornel",
"Cornelian Tree",
"Corydalis",
"Fern",
"Golden Corydalis",
"Pale Corydalis",
"Pink Corydalis",
"Yellow Corydalis",
"Creeping Yellowcress",
"Cress",
"American Cress",
"Bank Cress",
"Belle Isle Cress",
"Bermuda Cress",
"Bulbous Cress",
"Lamb's Cress",
"Land Cress",
"Scurvy Cress",
"Spring Cress",
"Upland Cress",
"Crowfoot",
"Crow's Nest",
"Crow's Toes",
"Daisy",
"Brown Daisy",
"Gloriosa Daisy",
"Nigger Daisy",
"Poorland Daisy",
"Yellow Daisy",
"Yellow Ox",
"Deadnettle",
"Henbit Deadnettle",
"Devil's Bite",
"Devil's Darning Needle",
"Devil's Hair",
"Devil's Plague",
"Dewberry",
"Bristly Dewberry",
"Swamp Dewberry",
"Dindle",
"Dogwood",
"American Dogwood",
"Florida Dogwood",
"Flowering Dogwood",
"Japanese Flowering Dogwood",
"Kousa Dogwood",
"Silky Dogwood",
"Swamp Dogwood",
"Duck Retten",
"Duscle",
"Dye",
"Earth Gall",
"English Bull's Eye",
"Fair",
"Fairymoss Azolla caroliniana",
"Fellenwort",
"Felonwood",
"Felonwort",
"Fern",
"Mosquito Fern",
"Water Fern",
"Feverbush",
"Feverfew",
"Fluxroot",
"Fumewort",
"Yellow Fumewort",
"Gallberry",
"Garget",
"Garlic",
"Golden Garlic",
"Wild Garlic",
"Garlic Mustard",
"Garlic Root",
"Gilliflower",
"Dame's Gilliflower",
"Night Scented Gilliflower",
"Queen's Gilliflower",
"Rogue's Gilliflower",
"Winter Gilliflower",
"Golden Buttons",
"Goldenglow",
"Golden Jerusalem",
"Gordaldo",
"Goose Tongue",
"Groundberry",
"Bristly Groundberry",
"Gutweed",
"Harlequin",
"Rock Harlequin",
"Yellow Harlequin",
"Hay Fever Weed",
"Healing Blade",
"Hedge Plant",
"Hellebore",
"American White Hellebore",
"Big Hellebore",
"Black Hellebore",
"European White Hellebore",
"False Hellebore",
"Swamp Hellebore",
"White Hellebore",
"Hemp Dogbane",
"Hen Plant",
"Henbit",
"Greater Henbit",
"Herb Barbara",
"Hogweed",
"Holly",
"Deciduous Holly",
"Inkberry Holly",
"Meadow Holly",
"Swamp Holly",
"Winterberry Holly",
"Horse Cane",
"Hound's Berry",
"Houseleek",
"Indian Hemp",
"White Indian Hemp",
"Indian Paintbrush",
"Indian Posy",
"Inkberry",
"Isle of Man Cabbage",
"Itchweed",
"Jack",
"Jack",
"Juneberry",
"Juniper",
"Keek",
"Kinnikinnik",
"Kousa",
"Kudzu",
"Laceflower",
"Lamb's Foot",
"Leek",
"Lily Leek",
"Lilac",
"Summer Lilac",
"Love Vine",
"Maple",
"Ash",
"Black Maple",
"Creek Maple",
"Cutleaf Maple",
"Maple Ash",
"Moose Maple",
"Red River Maple",
"River Maple",
"Silver Maple",
"Silverleaf Maple",
"Soft Maple",
"Striped Maple",
"Sugar Maple",
"Swamp Maple",
"Water Maple",
"White Maple",
"Mesquite",
"Honey Mesquite",
"Screwbean Mesquite",
"Milfoil",
"Milkweed",
"Blunt",
"Common Milkweed",
"Horsetail Milkweed",
"Orange Milkweed",
"Swamp Milkweed",
"Rose Milkweed",
"Whorled Milkweed",
"Yellow Milkweed",
"Milky Tassel",
"Moosewood",
"Morel",
"Petty Morel",
"Mosquito Plant",
"Mother",
"Mountain Mahogany",
"Mulberry",
"Red Mulberry",
"White Mulberry",
"Nature's Mistake",
"Nettle",
"Bull Nettle",
"Carolina Horse Nettle",
"Horse Nettle",
"Nightshade",
"American Nightshade",
"Bitter Nightshade",
"Black Nightshade",
"Climbing Nightshade",
"Deadly Nightshade",
"Garden Nightshade",
"Trailing Nightshade",
"Woody Nightshade",
"Nosebleed",
"Oak",
"Algerian Oak Quercus canariensis",
"Black Oak",
"Blue Oak",
"Bur Oak",
"Champion Oak",
"Dyer's Oak",
"English Oak",
"Mirbeck's Oak",
"Mossycup Oak",
"Mossycup White Oak",
"Pedunculate Oak",
"Pin Oak",
"Red Oak",
"Scarlet Oak",
"Scrub Oak",
"Sessile Oak",
"Spanish Oak",
"Spotted Oak",
"Swamp Oak",
"Swamp Spanish Oak",
"Swamp White Oak",
"White Oak",
"Yellowbark Oak",
"Old Man's Pepper",
"Onion",
"Giant Onion",
"Nodding Onion",
"Tree Onion",
"Wild Onion",
"Orange",
"Osage Orange",
"Wild Orange",
"Orange",
"Osage",
"Osier",
"Red Osier",
"Parsnip",
"Pellitory",
"Bastard Pellitory",
"European Pellitory",
"Wild Pellitory",
"Penny Hedge",
"Pepper Root",
"Pigeon Berry",
"Pine",
"Plane",
"Plantain",
"Broadleaf Plantain",
"Common Plantain",
"Dooryard Plantain",
"Greater Plantain",
"Roundleaf Plantain",
"Wayside Plantain",
"Pleurisy Root",
"Pocan Bush",
"Poisonberry",
"Poisonflower",
"Poke",
"Indian Poke",
"Pokeroot",
"Pokeweed",
"Polkweed",
"Polecat Weed",
"Poor Annie",
"Poor Man's Mustard",
"Poplar",
"Possumhaw",
"Queen Anne's Lace",
"Quercitron",
"Radical Weed",
"Ragweed",
"Common Ragweed",
"Giant Ragweed",
"Great Ragweed",
"Rantipole",
"Raspberry",
"Black Raspberry",
"Purple Raspberry",
"Redbrush",
"Red Ink Plant",
"Redweed",
"Rheumatism Root",
"Ribwort",
"Roadweed",
"Rocket",
"Dame's Rocket",
"Sweet Rocket",
"Winter Rocket",
"Yellow Rocket",
"Rocketcress",
"Rose",
"Baby Rose",
"Dwarf Wild Rose",
"Low Rose",
"Multiflora Rose",
"Prairie Rose",
"Rambler Rose",
"Wild Rose",
"Sanguinary",
"Sauce",
"Scarlet Berry",
"Scoke",
"Scotch Cap",
"Scrambled Eggs",
"Scurvy Grass",
"Serviceberry",
"Common Serviceberry",
"Downy Serviceberry",
"Shadblow Serviceberry",
"Shadblow",
"Shadbush",
"Silkweed",
"Swamp Silkweed",
"Virginia Silkweed",
"Skunkweed",
"Snakeberry",
"Snowdrop",
"Speedwell",
"Corn Speedwell",
"Wall Speedwell",
"Spoolwood",
"Squaw Bush",
"Stammerwort",
"Star",
"Stickweed",
"Swallow",
"Orange Swallow",
"Silky Swallow",
"Sneezeweed",
"Sneezewort",
"Sugarplum",
"Soldier's Woundwort",
"Stag Bush",
"Swallow",
"Orange Swallow",
"Silky Swallow",
"Sweet Potato",
"Sweet Potato Vine",
"Swinies",
"Tansy",
"Common Tansy",
"White Tansy",
"Wild Tansy",
"Tea",
"Appalachian Tea",
"Thimbleberry",
"Thimbleweed",
"Thousand",
"Thousand",
"Tassel Weed",
"Thistle",
"Annual Sow Thistle",
"California Thistle",
"Canada Thistle",
"Corn Thistle",
"Corn Sow Thistle",
"Creeping Thistle",
"Cursed Thistle",
"Field Sow Thistle",
"Green Thistle",
"Hard Thistle",
"Hare's Thistle",
"Milk Thistle",
"Nodding Thistle",
"Perennial Thistle",
"Prickly Thistle",
"Sharp",
"Small",
"Spiny Sow Thistle",
"Spiny",
"Swine Thistle",
"Tree Sow Thistle",
"Way Thistle",
"Tickleweed",
"Toothwort",
"Cutleaf Toothwort",
"Purple",
"Touch",
"Traveller's Joy",
"Tread",
"Tree Tobacco",
"Tuber",
"Tulip",
"Viburnum",
"Blackhaw Viburnum",
"Leatherleaf Viburnum",
"Violet",
"Damask Violet",
"Dame's Violet",
"Violet Bloom",
"Virgin's Bower",
"Virginia Virgin's Bower",
"Waybread",
"White Man's Foot",
"White",
"Wild Cotton",
"Wild Hops",
"Willow",
"Coyote Willow",
"Goodding Willow",
"Red Willow",
"Rose Willow",
"Windroot",
"Wineberry",
"Winterberry",
"American Winterberry",
"Evergreen Winterberry",
"Virginia Winterberry",
"Wintercress",
"Early Wintercress",
"Woodbine",
"Wormwood",
"Roman Wormwood",
"Wound Rocket",
"Yarrow",
"Common Yarrow",
"Fernleaf Yarrow",
"Sneezewort Yarrow",
"Yellow Fieldcress",
"Yellowwood",
"Yellow Coneflower",
"Zinnia",
*/
    0
};

static const char *adjectives[] = 
{
    "Acclaimed",
    "Agley",
    "Angry",
    "Reanimated",
    "Aristocratic",
    "Atrocious",
    "August",
    "Authoritative",
    "Azure",
    "Baneful",
    "Baronial",
    "Base",
    "Beastly",
    "Bedraggled",
    "Begrimed",
    "Beryl",
    "Bittersweet",
    "Black",
    "Bloodshot",
    "Blooming",
    "Blue",
    "Gray",
    "Emerald",
    "Bony",
    "Brilliant",
    "Cacodemonic",
    "Cadaverous",
    "Calamitous",
    "Cardinal",
    "Celebrated",
    "Cerulean",
    "Cobalt",
    "Commanding",
    "Conspicuous",
    "Coral",
    "Corrupt",
    "Crimson",
    "Dahlia",
    "Damnable",
    "Defiled",
    "Demonic",
    "Desolate",
    "Destructive",
    "Devilish",
    "Diabolic",
    "Dignified",
    "Dirty",
    "Disastrous",
    "Dismal",
    "Distinguished",
    "Dreary",
    "Elevated",
    "Eminent",
    "Energumenical",
    "Especial",
    "Esteemed",
    "Evil",
    "Execrable",
    "Extraordinary",
    "Famed",
    "Famous",
    "Filthy",
    "Flagitious",
    "Flaming",
    "Florid",
    "Flushed",
    "Forbidding",
    "Foremost",
    "Forlorn",
    "Foul",
    "Garnet",
    "Glorious",
    "Glowing",
    "Goetic",
    "Grandiose",
    "Great",
    "Grim",
    "Haggard",
    "Harsh",
    "Hateful",
    "Heinous",
    "Hell",
    "Hideous",
    "High",
    "Highborn",
    "Highly-Regarded",
    "Holy",
    "Honorable",
    "Honored",
    "Illustrious",
    "Immoral",
    "Imperial",
    "Imposing",
    "Impressive",
    "Impure",
    "Indigo",
    "Inflamed",
    "Iniquitous",
    "Injurious",
    "Kingly",
    "Lenocinant",
    "Loathsome",
    "Lofty",
    "Low",
    "Magnificent",
    "Majestic",
    "Malefic",
    "Maleficent",
    "Malevolent",
    "Malicious",
    "Malignant",
    "Malominous",
    "Meager",
    "Miry",
    "Murky",
    "Nasty",
    "Navy",
    "Nefarious",
    "Noble",
    "Nonpareil",
    "Noteworthy",
    "Obscene",
    "Offensive",
    "Outstanding",
    "Peccant",
    "Peerless",
    "Pernicious",
    "Poison",
    "Polluted",
    "Prominent",
    "Putrid",
    "Queenly",
    "Rancorous",
    "Raunchy",
    "Red",
    "Regal",
    "Regnant",
    "Reigning",
    "Remarkable",
    "Renowned",
    "Reprobate",
    "Repugnant",
    "Resplendent",
    "Revolting",
    "Rose",
    "Roseate",
    "Royal",
    "Rubicund",
    "Ruby",
    "Ruling",
    "Rusty",
    "Sanguine",
    "Sapphire",
    "Satanic",
    "Scarlet",
    "Scelerate",
    "Sea-blue",
    "Shining",
    "Sinful",
    "Singular",
    "Sinistral",
    "Skeletal",
    "Soiled",
    "Sovereign",
    "Spare",
    "Spiteful",
    "Splendid",
    "Squalid",
    "Stained",
    "Stately",
    "Stinking",
    "Striking",
    "Superb",
    "Superior",
    "Supreme",
    "Teal",
    "Titian",
    "Tortious",
    "Turquoise",
    "Ugly",
    "Ultramarine",
    "Unclean",
    "Undead",
    "Unforgettable",
    "Unholy",
    "Unpleasant",
    "Unpropitious",
    "Unsightly",
    "Unwashed",
    "Venal",
    "Venerable",
    "Vermilion",
    "Verminous",
    "Vicious",
    "Vile",
    "Villainous",
    "Wasted",
    "Well-known",
    "Wicked",
    "Worthy",
    "Wrathful",
    "Wrong",
    "Zoetic",
/*

"Air Force blue",
"Alice blue",
"Alizarin",
"Amaranth",
"Amaranth cerise",
"Amaranth deep purple",
"Amaranth magenta",
"Amaranth pink",
"Amaranth purple",
"Amber",
"Amber (SAE/ECE)",
"American rose",
"Amethyst",
"Android Green",
"Anti-flash white",
"Antique white",
"Apple green",
"Apricot",
"Aqua",
"Aquamarine",
"Army green",
"Arsenic",
"Asparagus",
"Atomic tangerine",
"Auburn",
"Azure (color wheel)",
"Azure mist",
"Baby blue",
"Baby pink",
"Battleship grey",
"Beige",
"Bistre",
"Bittersweet",
"Black",
"Blue",
"Blue (pigment)",
"Blue (RYB)",
"Blue-green",
"Blue-violet",
"Bole",
"Bondi blue",
"Boston University Red",
"Brandeis Blue",
"Brass",
"Brick red",
"Bright cerulean",
"Bright green",
"Bright lavender",
"Bright maroon",
"Bright pink",
"Bright turquoise",
"Bright ube",
"Brilliant rose",
"Brink Pink",
"British racing green",
"Bronze",
"Brown (traditional)",
"Brown (web)",
"Buff",
"Bulgarian Rose",
"Burgundy",
"Burnt orange",
"Burnt sienna",
"Burnt umber",
"Byzantine",
"Byzantium",
"Cadet blue",
"Cadmium Green",
"Cadmium Orange",
"Cadmium Red",
"Cadmium Yellow",
"Cambridge Blue",
"Camel",
"Camouflage green",
"Caput mortuum",
"Cardinal",
"Carmine",
"Carmine pink",
"Carmine red",
"Carnation pink",
"Carnelian",
"Carolina blue",
"Caribbean green",
"Carrot orange",
"Ceil",
"Celadon",
"Cerise",
"Cerise pink",
"Cerulean",
"Cerulean blue",
"Chamoisee",
"Champagne",
"Charcoal",
"Chartreuse (traditional)",
"Chartreuse (web)",
"Cherry blossom pink",
"Chestnut",
"Chocolate",
"Cinereous",
"Cinnabar",
"Cinnamon",
"Citrine",
"Classic rose",
"Cobalt",
"Columbia blue",
"Cool black",
"Cool grey",
"Copper",
"Copper rose",
"Coquelicot",
"Coral",
"Coral pink",
"Coral red",
"Cordovan",
"Corn",
"Cornsilk",
"Cornflower blue",
"Cosmic latte",
"Cotton candy",
"Cream",
"Crimson",
"Crimson glory",
"Cyan",
"Cyan (process)",
"Dandelion",
"Dark blue",
"Dark brown",
"Dark byzantium",
"Dark cerulean",
"Dark champagne",
"Dark chestnut",
"Dark coral",
"Dark cyan",
"Dark electric blue",
"Dark goldenrod",
"Dark green",
"Dark jungle green",
"Dark khaki",
"Dark lava",
"Dark lavender",
"Dark magenta",
"Dark midnight blue",
"Dark orange",
"Dark pastel green",
"Dark pink",
"Dark powder blue",
"Dark raspberry",
"Dark red",
"Dark salmon",
"Dark scarlet",
"Dark sienna",
"Dark slate gray",
"Dark spring green",
"Dark tan",
"Dark tangerine",
"Dark taupe",
"Dark terra cotta",
"Dark turquoise",
"Dark violet",
"Dartmouth green",
"Davy's grey",
"Deep carmine",
"Deep carmine pink",
"Deep carrot orange",
"Deep cerise",
"Deep champagne",
"Deep chestnut",
"Deep fuchsia",
"Deep jungle green",
"Deep lilac",
"Deep magenta",
"Deep peach",
"Deep pink",
"Deep saffron",
"Deep sky blue",
"Denim",
"Desert",
"Desert sand",
"Dim gray",
"Dodger blue",
"Dogwood Rose",
"Drab",
"Duke blue",
"Earth yellow",
"Ecru",
"Eggplant",
"Eggshell",
"Egyptian blue",
"Electric blue",
"Electric green",
"Electric indigo",
"Electric lime",
"Electric purple",
"Electric violet",
"Emerald",
"Eton blue",
"Fallow",
"Falu red",
"Fandango",
"Fashion fuchsia",
"Fawn",
"Feldgrau",
"Fern green",
"Field drab",
"Firebrick",
"Fire engine red",
"Flame",
"Flamingo pink",
"Flavescent",
"Flax",
"Forest green (traditional)",
"Forest green (X11)",
"French Beige",
"French Rose",
"Fuchsia",
"Fuchsia Pink",
"Fulvous",
"Gamboge",
"Ghost white",
"Glaucous",
"Gold (metallic)",
"Gold (web) (Golden)",
"Golden brown",
"Golden poppy",
"Golden yellow",
"Goldenrod",
"Gray",
"Gray-asparagus",
"Green (color wheel) (X11 green)",
"Green (HTML/CSS green)",
"Green (pigment)",
"Green (RYB)",
"Green-yellow",
"Grullo",
"Halaya ube",
"Han Blue",
"Han Purple",
"Harlequin",
"Heliotrope",
"Hollywood cerise",
"Honeydew",
"Hot magenta",
"Hot pink",
"Hunter green",
"Iceberg",
"Icterine",
"India green",
"Indian yellow",
"Indigo (dye)",
"Indigo (web)",
"International Klein Blue",
"International orange",
"Iris",
"Isabelline",
"Islamic green",
"Ivory",
"Jade",
"Jazzberry jam",
"Jonquil",
"June bud",
"Jungle green",
"Kelly green",
"Khaki",
"Khaki (X11) (Light khaki)",
"Languid lavender",
"Lava",
"Lavender (floral)",
"Lavender (web)",
"Lavender blue",
"Lavender Blush",
"Lavender gray",
"Lavender indigo",
"Lavender magenta",
"Lavender pink",
"Lavender purple",
"Lavender rose",
"Lawn green",
"Lemon",
"Lemon chiffon",
"Light apricot",
"Light blue",
"Light carmine pink",
"Light coral",
"Light cornflower blue",
"Light fuchsia pink",
"Light mauve",
"Light pink",
"Light sea green",
"Light salmon",
"Light salmon pink",
"Light sky blue",
"Light slate gray",
"Light Thulian pink",
"Lilac",
"Lime (color wheel)",
"Lime (web) (X11 green)",
"Lime green",
"Linen",
"Liver",
"Lust",
"Magenta",
"Magenta (dye)",
"Magenta (process)",
"Magic mint",
"Magnolia",
"Mahogany",
"Maize",
"Majorelle Blue",
"Malachite",
"Maroon (HTML/CSS)",
"Maroon (X11)",
"Mauve",
"Mauve taupe",
"Maya blue",
"Medium blue",
"Medium carmine",
"Medium champagne",
"Medium electric blue",
"Medium jungle green",
"Medium lavender magenta",
"Medium Persian blue",
"Medium purple",
"Medium red-violet",
"Medium sea green",
"Medium spring bud",
"Medium spring green",
"Medium taupe",
"Medium teal blue",
"Medium turquoise",
"Midnight blue",
"Midnight green (eagle green)",
"Mikado yellow",
"Mint green",
"Misty rose",
"Moccasin",
"Mode Beige",
"Moss green",
"Mountbatten pink",
"Mulberry",
"Mustard",
"Myrtle",
"MSU Green",
"Nadeshiko pink",
"Napier Green",
"Navajo white",
"Navy Blue",
"Ochre",
"Office green",
"Old Gold",
"Old Lace",
"Old lavender",
"Old Rose",
"Olive",
"Olive Drab",
"Olive Drab",
"Olivine",
"Onyx",
"Opera mauve",
"Orange (color wheel)",
"Orange (RYB)",
"Orange (web color)",
"Orange peel",
"Orange-red",
"Orchid",
"Oxford Blue",
"Pale Amaranth Pink",
"Pale blue",
"Pale brown",
"Pale carmine",
"Pale cerulean",
"Pale chestnut",
"Pale copper",
"Pale cornflower blue",
"Pale gold",
"Pale magenta",
"Pale pink",
"Pale red-violet",
"Pale robin egg blue",
"Pale silver",
"Pale spring bud",
"Pale taupe",
"Palatinate blue",
"Palatinate purple",
"Pansy purple",
"Papaya whip",
"Pastel green",
"Pastel pink",
"Payne's grey",
"Peach",
"Peach-orange",
"Peach puff",
"Peach-yellow",
"Pear",
"Pearl",
"Periwinkle",
"Persian blue",
"Persian green",
"Persian indigo",
"Persian orange",
"Persian red",
"Persian pink",
"Persian rose",
"Persimmon",
"Phthalo blue",
"Phthalo green",
"Piggy pink",
"Pine green",
"Pink",
"Pink-orange",
"Pistachio",
"Platinum",
"Plum (web)",
"Portland Orange",
"Powder blue (web)",
"Princeton Orange",
"Prussian blue",
"Psychedelic purple",
"Puce",
"Pumpkin",
"Purple (HTML/CSS)",
"Purple (X11)",
"Purple Heart",
"Purple taupe",
"Radical Red",
"Raspberry",
"Raspberry glace",
"Raspberry pink",
"Raspberry rose",
"Raw umber",
"Razzle dazzle rose",
"Razzmatazz",
"Red",
"Red (pigment)",
"Red (RYB)",
"Red-violet",
"Rich black",
"Rich carmine",
"Rich electric blue",
"Rich lavender",
"Rich maroon",
"Rifle green",
"Robin egg blue",
"Rose",
"Rose Ebony",
"Rose Gold",
"Rose Madder",
"Rose pink",
"Rose quartz",
"Rose taupe",
"Rose Vale",
"Rosewood",
"Rosy Brown",
"Royal blue (traditional)",
"Royal blue (web color)",
"Royal fuchsia",
"Royal purple",
"Ruby",
"Rufous",
"Russet",
"Rust",
"Sacramento State green",
"Saddle brown",
"Safety orange (blaze orange)",
"Saffron",
"St. Patrick's blue",
"Salmon",
"Salmon pink",
"Sand",
"Sand dune",
"Sandy brown",
"Sandy taupe",
"Sangria",
"Sap green",
"Sapphire",
"Satin sheen gold",
"Scarlet",
"School bus yellow",
"Sea green",
"Seal brown",
"Seashell",
"Selective yellow",
"Sepia",
"Shamrock green",
"Shocking pink",
"Sienna",
"Silver",
"Skobeloff",
"Sky blue",
"Sky magenta",
"Slate gray",
"Smalt (Dark powder blue)",
"Smoky black",
"Snow",
"Splashed white",
"Spring bud",
"Spring green",
"Steel blue",
"Straw",
"Sunglow",
"Sunset",
"Tan",
"Tangelo",
"Tangerine",
"Tangerine yellow",
"Taupe",
"Taupe gray",
"Tea green",
"Tea rose (orange)",
"Tea rose (rose)",
"Teal",
"Teal blue",
"Tenné (Tawny)",
"Terra cotta",
"Thistle",
"Thulian pink",
"Tiffany Blue",
"Tomato",
"Torch red",
"Tropical rain forest",
"Turkish Rose",
"Turquoise",
"Turquoise blue",
"Tuscan red",
"Twilight lavender",
"Tyrian purple",
"Ube",
"Ultramarine",
"Ultra pink",
"United Nations blue",
"Upsdell red",
"Vegas Gold",
"Venetian red",
"Vermilion",
"Violet",
"Violet (color wheel)",
"Violet (web)",
"Violet (RYB)",
"Viridian",
"Vivid auburn",
"Vivid burgundy",
"Vivid violet",
"Warm black",
"Wenge",
"Wheat",
"White",
"White smoke",
"Wisteria",
"Xanadu",
"Yale Blue",
"Yellow",
"Yellow (process)",
"Yellow (RYB)",
"Yellow-green",
*/
    0
};

static const char *names[] =
{
    ".Attila",
    ".Bones",
    ".Bugul-Noz",
    ".Diavolus",
    ".Fenris",
    ".Lilith",
    ".Lucius",
    ".Lucretia",
    ".Machiavelli",
    ".Man",
    ".Manichea",
    ".Pan",
    ".Pandora",
    ".Talos",
    ".Tarquinius",
    ".Typhon",
    ".Woman",
    ".Xana",
    ".Zana",
    "Air-Elemental",
    "Angel",
    "Ankou",
    "Arachnid",
    "Arion",
    "Asp",
    "Axe",
    "Balrog",
    "Banshee",
    "Barbarian",
    "Basilisk",
    "Beast",
    "Behemoth",
    "Black-Annis",
    "Bone-Cage",
    "Boor",
    "Brute",
    "Cadaver",
    "Cannibal",
    "Carcass",
    "Cecaelia",
    "Centaur",
    "Changeling",
    "Child",
    "Chimaera",
    "Cockatrice",
    "Corpse",
    "Creature",
    "Critter",
    "Crocotta",
    "Crow",
    "Cwn-Annwn",
    "Cyclops",
    "Daemon",
    "Dahlia",
    "Daphnaie",
    "Dark-Elf",
    "Dead",
    "Dead-Body",
    "Deceased",
    "Demigod",
    "Demon",
    "Devil",
    "Diavolus",
    "Drac",
    "Dragon",
    "Drake",
    "Dryad",
    "Duende",
    "Dvergr",
    "Dwarf",
    "Earth-Elemental",
    "Elephant",
    "Elf",
    "Enchanted",
    "Ettin",
    "Fachen",
    "Fairy",
    "Familiar",
    "Faun",
    "Fiend",
    "Fire-Elemental",
    "Fire-Giant",
    "Firedrake",
    "Flesh",
    "Flesh-and-Blood",
    "Fool",
    "Fox",
    "Frost-Giant",
    "Gargoyle",
    "Garmr",
    "Genius-Loci",
    "Ghost",
    "Ghoul",
    "Giant",
    "Gigantes",
    "Glutton",
    "Gnome",
    "Goblin",
    "Golem",
    "Gorgades",
    "Gorgon",
    "Gravedigger",
    "Gryphon",
    "Gwyllgi",
    "Gwyllion",
    "Hag",
    "Half-Elf",
    "Hamadryad",
    "Hellhound",
    "Hesperides",
    "Hob",
    "Hobgoblin",
    "Hog",
    "Homunculus",
    "Hooligan",
    "Houri",
    "Hun",
    "Hydra",
    "Ice-Giant",
    "Ignoramus",
    "Incubus",
    "Indus-Worm",
    "Jaculus",
    "Jormungandr",
    "King",
    "Knocker",
    "Kobold",
    "Kraken",
    "Ladon",
    "Lady-Midday",
    "Landvaettir",
    "Leviathan",
    "Lily",
    "Lizard",
    "Ljosalfar",
    "Llorona",
    "Lout",
    "Lynx",
    "Macrocephali",
    "Mage",
    "Magician",
    "Mandrake",
    "Manes",
    "Manticore",
    "Mara",
    ".Medusa",
    "Meliae",
    ".Melusine",
    ".Mephisto",
    "Minotaur",
    "Monocerus",
    "Monopod",
    "Monster",
    "Monstrosity",
    "Mortal",
    "Muse",
    "Naiad",
    "Necromancer",
    "Nephilim",
    "Nereid",
    "Nix",
    "Nymph",
    "Ogre",
    "Orc",
    "Ouroboros",
    "Patagon",
    "Pegasus",
    "Philistine",
    "Phoenix",
    "Pig",
    "Pixie",
    "Poltergeist",
    "Prince",
    "Princess",
    "Pygmy",
    "Quadruped",
    "Queen",
    "Quinotaur",
    "Rarog",
    "Rascal",
    "Raven",
    "Remains",
    "Revenant",
    "Rok",
    "Rose",
    "Ruffian",
    "Salamander",
    "Satyr",
    "Satyrus",
    "Scorpion",
    "Seductress",
    "Serpent",
    "Shade",
    "Shipwreck",
    "Siren",
    "Sjoraa",
    "Sjovaettir",
    "Skeleton",
    "Skogsraa",
    "Sloven",
    "Snake",
    "Soul",
    "Spectre",
    "Sphinx",
    "Spider",
    "Sprite",
    "Stiff",
    "Succubus",
    "Svartalfar",
    "Swan-Maiden",
    "Swine",
    "Sword",
    "Troglodyte",
    "Troll",
    ".Tzitzimitl",
    "Undead",
    ".Undine",
    "Unicorn",
    "Vaettir",
    "Valkyrie",
    "Vandal",
    "Varmint",
    "Viper",
    "Vital-Spark",
    "Warg",
    "Warthog",
    "Water-Elemental",
    "White-Lady",
    "Wight",
    "Wizard",
    "Worm",
    "Wraith",
    "Wyrm",
    "Wyvern",
    "Zombie",
/*
"Aardvark",
"Aardwolf",
"AfghanHound",
"Albatross",
"Alligator",
"Alpaca",
"Anaconda",
"Angelfish",
"Anglerfish",
"Ant",
"Anteater",
"Antelope",
"Antlion",
"Ape",
"Aphid",
"Armadillo",
"Arrowcrab",
"Asp",
"Ass",
"Baboon",
"Badger",
"BaldEagle",
"Bandicoot",
"Barnacle",
"Barracuda",
"Basilisk",
"Bass",
"BassetHound",
"Bat",
"Beakedwhale",
"Bear",
"Beaver",
"Bedbug",
"Bee",
"Beetle",
"Bird",
"Bison",
"BlackWidowSpider",
"Blackbird(NewWorld)",
"Blackbird(OldWorld)",
"Blackpanther",
"BlueJay",
"BlueWhale",
"Boa",
"Bobcat",
"Bobolink",
"Bonobo",
"Booby",
"BostonTerrier",
"Bovid",
"Boxjellyfish",
"Buffalo",
"Bug",
"BullTerrier",
"Bulldog",
"Butterfly",
"Buzzard",
"Camel",
"Canid",
"CapeBuffalo",
"Cardinal",
"Caribou",
"Carp",
"Cat",
"Caterpillar",
"Catfish",
"Centipede",
"Cephalopod",
"Chameleon",
"Cheetah",
"Chickadee",
"Chicken",
"Chihuahua",
"Chimpanzee",
"Chinchilla",
"Chipmunk",
"Clam",
"Clownfish",
"Cobra",
"Cockroach",
"Cod",
"Collie",
"Condor",
"Constrictor",
"Coral",
"Cougar",
"Cow",
"Coyote",
"Crab",
"Crane",
"CraneFly",
"Crawdad",
"Crayfish",
"Cricket",
"Crocodile",
"Crow",
"Cuckoo",
"Daddylonglegs",
"Damselfly",
"Deer",
"Dingo",
"Dinosaur",
"Dog",
"Dolphin",
"Donkey",
"Dormouse",
"Dove",
"Dragonfly",
"Duck",
"Dungbeetle",
"Eagle",
"Earthworm",
"Earwig",
"Echidna",
"Eel",
"Egret",
"Elephant",
"Elephantseal",
"Elk",
"Emu",
"EnglishSetter",
"Englishpointer",
"Ermine",
"Falcon",
"Ferret",
"Finch",
"Firefly",
"Fish",
"Flamingo",
"Flea",
"Fly",
"Flyingfish",
"Fowl",
"Fox",
"Frog",
"FruitBat",
"Gazelle",
"Gecko",
"Gerbil",
"GermanShepherd",
"GiantPanda",
"Giantsquid",
"Gibbon",
"Gilamonster",
"Giraffe",
"Goat",
"GoldenRetriever",
"Goldfinch",
"Goldfish",
"Goose",
"Gopher",
"Gorilla",
"Grasshopper",
"GreatBlueHeron",
"GreatDane",
"Greatwhiteshark",
"Greyhound",
"GrizzlyBear",
"Grouse",
"Guanaco",
"Guineafowl",
"Guineapig",
"Gull",
"Guppy",
"Haddock",
"Halibut",
"Hammerheadshark",
"Hamster",
"Hare",
"Harrier",
"Hawk",
"Hedgehog",
"Hermitcrab",
"Heron",
"Herring",
"Hippopotamus",
"Hookworm",
"Hornet",
"Horse",
"Hound",
"Human",
"Hummingbird",
"HumpbackWhale",
"Husky",
"Hyena",
"Iguana",
"Impala",
"Insect",
"IrishSetter",
"IrishWolfhound",
"Irukandjijellyfish",
"Jackal",
"Jaguar",
"Jay",
"Jellyfish",
"Kangaroo",
"Kangaroomouse",
"Kangaroorat",
"Kingfisher",
"Kite",
"Kiwi",
"Koala",
"Koi",
"Komododragon",
"Krill",
"LabradorRetriever",
"Ladybug",
"Lamprey",
"Lark",
"Leech",
"Lemming",
"Lemur",
"Leopard",
"Leopon",
"Liger",
"Lion",
"Lizard",
"Llama",
"Lobster",
"Locust",
"Loon",
"Louse",
"Lungfish",
"Lynx",
"Macaw",
"Mackerel",
"Magpie",
"Mammal",
"Mammoth",
"MantaRay",
"Marlin",
"Marmoset",
"Marmot",
"Marsupial",
"Marten",
"Mastiff",
"Mastodon",
"Meadowlark",
"Meerkat",
"Mink",
"Minnow",
"Mite",
"Mockingbird",
"Mole",
"Mollusk",
"Mongoose",
"Monitorlizard",
"Monkey",
"Moose",
"Mosquito",
"Moth",
"Mountaingoat",
"Mouse",
"Mule",
"Muskox",
"Mussel",
"Narwhal",
"Newt",
"Nightingale",
"Ocelot",
"Octopus",
"OldEnglishSheepdog",
"Opossum",
"Orangutan",
"Orca",
"Ostrich",
"Otter",
"Owl",
"Ox",
"Oyster",
"Panda",
"Panther",
"Pantherahybrid",
"Parakeet",
"Parrot",
"Parrotfish",
"Partridge",
"Peacock",
"Peafowl",
"Pekingese",
"Pelican",
"Penguin",
"Perch",
"PeregrineFalcon",
"PersianCat",
"Pheasant",
"Pig",
"Pigeon",
"Pike",
"Pilotwhale",
"Pinniped",
"Piranha",
"Planarian",
"Platypus",
"Polarbear",
"Pony",
"Poodle",
"Porcupine",
"Porpoise",
"PortugueseMano'War",
"Possum",
"Prairiedog",
"Prawn",
"PrayingMantis",
"Primate",
"Puffin",
"Puma",
"Python",
"Quail",
"Rabbit",
"Raccoon",
"Rainbowtrout",
"Rat",
"Rattlesnake",
"Raven",
"Ray(Batoidea)",
"Ray(Rajiformes)",
"RedPanda",
"Reindeer",
"Rhinoceros",
"Rightwhale",
"Roadrunner",
"Robin",
"Rodent",
"Rook",
"Rooster",
"Roundworm",
"Saber-toothedcat",
"Sailfish",
"SaintBernard",
"Salamander",
"Salmon",
"Sawfish",
"Scaleinsect",
"Scallop",
"Scorpion",
"Seacow",
"Seahorse",
"Sealion",
"Seaslug",
"Seaurchin",
"Setter",
"Shark",
"Sheep",
"Shrew",
"Shrimp",
"SiameseCat",
"Silkworm",
"Silverfish",
"Skink",
"Skunk",
"Sloth",
"Slug",
"Smelt",
"Snail",
"Snake",
"Snipe",
"SnowLeopard",
"Sockeyesalmon",
"Sole",
"Spaniel",
"Sparrow",
"Spermwhale",
"Spider",
"Spidermonkey",
"Spoonbill",
"Squid",
"Squirrel",
"Star-nosedMole",
"Starfish",
"Steelheadtrout",
"Stingray",
"Stoat",
"Stork",
"Sturgeon",
"SugarGlider",
"Swallow",
"Swan",
"Swift",
"Swordfish",
"Swordtail",
"Tabbycat",
"Tahr",
"Takin",
"Tapeworm",
"Tapir",
"Tarantula",
"TasmanianDevil",
"Termite",
"Tern",
"Terrier",
"Thrush",
"Tick",
"Tiger",
"Tigershark",
"Tigon",
"Toad",
"Tortoise",
"Toucan",
"ToyPoodle",
"Trapdoorspider",
"Treefrog",
"Trout",
"Tuna",
"Turkey",
"Turtle",
"Tyrannosaurus",
"Urial",
"Vampirebat",
"Viper",
"Vole",
"Vulture",
"Wallaby",
"Walrus",
"Warbler",
"Wasp",
"WaterBuffalo",
"Weasel",
"Whale",
"Whitefish",
"WhoopingCrane",
"Wildcat",
"Wildebeest",
"Wildfowl",
"Wolf",
"Wolverine",
"Wombat",
"Woodpecker",
"Worm",
"Wren",
"Yak",
"Zebra",
*/
    0
};

static int GetCount(const char **list)
{
    const char **p = list;
    int i = 0;
    for (; *p; i++) p++;
    return i;
}

PlaceNameGenerator::PlaceNameGenerator() : mAdjectivesCount(0), mPlaceNamesCount(0), mNamesCount(0)
{
    mAdjectivesCount = GetCount(adjectives);
    mPlaceNamesCount = GetCount(placeNames);
    mNamesCount      = GetCount(names);
}

const char *PlaceNameGenerator::FormatName2(const char *adjective, const char *placeName, const char *name)
{
    static char buffer[1024];

    bool        placeNameThe = *placeName != '.',
                nameThe      = *name      != '.';

    const char *separator    = " ";

    if (!placeNameThe) placeName++;
    if (!nameThe)      name++;
    if (!adjective)    { adjective = ""; separator = ""; }

    if      (nameThe)
        sprintf(buffer, "The %s's %s%s%s", name, adjective, separator, placeName);
    else if (!nameThe)
        sprintf(buffer, "%s's %s%s%s", name, adjective, separator, placeName);
    /*
    else if (!placeNameThe &&  nameThe)
        //sprintf(buffer, "%s %s of the %s", adjective, placeName, name);
        sprintf(buffer, "%s of the %s", placeName, name);
    else if (!placeNameThe && !nameThe)
        //sprintf(buffer, "%s %s of %s", adjective, placeName, name);
        sprintf(buffer, "%s of %s", placeName, name);
    */

    return buffer;
}

const char *PlaceNameGenerator::FormatName1(const char *adjective, const char *placeName, const char *name)
{
    static char buffer[1024];

    bool        placeNameThe = *placeName != '.',
                nameThe      = *name      != '.';

    const char *separator    = " ";

    if (!placeNameThe) placeName++;
    if (!nameThe)      name++;
    if (!adjective)    { adjective = ""; separator = ""; }

    if      ( placeNameThe &&  nameThe)
        sprintf(buffer, "The %s%s%s of the %s", adjective, separator, placeName, name);
    else if ( placeNameThe && !nameThe)
        sprintf(buffer, "The %s%s%s of %s", adjective, separator, placeName, name);
    else if (!placeNameThe &&  nameThe)
        sprintf(buffer, "%s%s%s of the %s", adjective, separator, placeName, name);
    else if (!placeNameThe && !nameThe)
        sprintf(buffer, "%s%s%s of %s", adjective, separator, placeName, name);

    return buffer;
}

const char *PlaceNameGenerator::GetPlaceName(core::Random &random)
{
    int number0 = random.integer(),
        number1 = random.integer(),
        number2 = random.integer();

    const char *adjective = adjectives[number0 % mAdjectivesCount];
    const char *placeName = placeNames[number1 % mPlaceNamesCount];
    const char *name      = names     [number2 % mNamesCount];

    if (random.realf() < 0.5f) adjective = 0;

    const char *formatted = 0;
    if (random.realf() < 0.5f) formatted = FormatName1(adjective, placeName, name);
    else                       formatted = FormatName2(adjective, placeName, name);

    strcpy(mName, formatted);
    return mName;
}